### ISSUE TITLE
Add fields for feature funders and developers

### ISSUE THREAD

**Issue by vpicavet** [kartoza/projecta#102]
It would be a great incentive for project funders if their name could be listed along each feature listed, with a link to their website.

As well, it would also be a strong incentive and recognition to mention developers/companies having done the development of the features. Links to developer's github accounts and companies website is a plus.

The result could be a simple line at the bottom of a feature entry like the following : 
"This feature has seen light thanks to funding from funderA, funderB and funderC, and development by developer1, developer2 ( company1), developer3 (company2) and developer4."

Adding somewhere at the top or the bottom the full generated list of developers who contributed to the release would be a great addition too.

**Comment by timlinux** [comment]
Note we have discussed this on QGIS PSC meeting. For now please simply add text at the bottom of your entry in a standard form e.g.

**Funded by:** Foo corp
**Implemented by:** John doe

**Comment by timlinux** [comment]
So just to update the requirements here:

- [ ] Add a field to the entry model for 'funded_by'
- [ ] Add a field to the entry model for 'funder_url'
- [ ] Add a field to the entry model for 'developed_by'
- [ ] Add a field to the entry model for 'developer_url'

All fields should be optional.

Then add a method to the model called 'funder_info_html' which will render html with the following forms:

* return empty string if funded_by, developed_by, funder_url and developer_url are all None
* If funded_by and funder_url are populated, return ```This feature was funded by (%s)[%s]' % (self.funded_by, self.funder_url)```
* If funded_by is populated only, return ```This feature was funded by %s' % (self.funded_by, self.funder_url)```
* If  funder_url are populated only, return ```This feature was funded by (%s)[%s]' % (self.funded_url, self.funder_url)```

Create a similar method for markdown rendering which should be rendered into the markdown output.

The same pattern should be followed for the developer_info.

And then to the template for entry, we should add:

```
{{ entry.funder_info_html }}
{{ entry.developer_info_html }}
```
to the bottom of the entry

**Comment by rischanlab** [comment]
This is the screenshoot, probably you have some comment @timlinux 

![screen shot 2015-10-21 at 10 25 38 pm](https://cloud.githubusercontent.com/assets/2235894/10641644/450daf8c-7844-11e5-9603-d3f3aa52bb63.png)

**Comment by vpicavet** [comment]
Hi, could we have a small picture for logos beside funder and developer ?
