### ISSUE TITLE
added entries not visible

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#104]
I've added two entries, with as Title:
Processing: New modeler
and
Processing: On-line collection of models and scripts
both are not visible (to me), not in the approved entries, not in the pending approval entries.
BUT if I try new entries with those same Feature Title, I get an error: 
"Entry with this Title already excists"
Also if I log out, I cannot see this entries though

**Comment by timlinux** [comment]
I believe this was due to no pagination widget - I set the pagination size to a very large number. Thanks!
