### ISSUE TITLE
Wrong links to images from entry page

### ISSUE THREAD

**Issue by blazek** [kartoza/projecta#105]
If I open an entry page, for example 
    http://changelog.linfiniti.com/qgis/2.8/entry/more-responsive-browser/ and then click on the image I get server error 404 because the link is pointing to 
    /qgis/2.8/entry/<entry name>/images/entries/<hash>.<ext>
instead of 
    /media/images/entries/<hash>.<ext>

**Comment by timlinux** [comment]
Note that it works fine if you go in via:

http://changelog.linfiniti.com/qgis/version/2.8/

Then click on the image.

@ismailsunni we need to get rid of all that middleware black magick and make our navitation system much simpler.
