### ISSUE TITLE
Unable to edit Online training center

### ISSUE THREAD

**Issue by spatialthoughts** [kartoza/projecta#1179]
I created a training center 'Online' but unable to edit it. Might have something to do with the address.
https://changelog.qgis.org/en/qgis/certifyingorganisation/spatial-thoughts/trainingcenter/online/update/

**Comment by spatialthoughts** [comment]
<img width="852" alt="Screen Shot 2020-04-24 at 7 49 07 PM" src="https://user-images.githubusercontent.com/5227506/80222599-bb924b80-8664-11ea-8f3e-c7b5de012801.png">

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/80289796-09788380-8739-11ea-93da-0d1716ba6912.png)

@ann26 can you look into this please? Also more generally we need to figure out a nicer way to accommodate 'online' as a training center.

See https://changelog.qgis.org/en/site-admin/certification/trainingcenter/91/change/ - the recrod seems to have been created properly.

**Comment by anitanh** [comment]
should be fixed now @spatialthoughts
