### ISSUE TITLE
Submit button in form for training registration is not visible on FF

### ISSUE THREAD

**Issue by elpaso** [kartoza/projecta#1182]
Looks like it's covered by the chat footer

![immagine](https://user-images.githubusercontent.com/142164/81825228-ac514000-9536-11ea-9b4e-2b9b428afd93.png)

**Comment by timlinux** [comment]
Hi @elpaso thanks for the report - @ann26 will you look please?

**Comment by Ojaybee** [comment]
I was finding this on FF and Chrome (using a windows laptop). If you zoom the page out (ctrl + scroll wheel) the submit button is revealed under the footer

**Comment by anitanh** [comment]
hi @elpaso and @Ojaybee I've fixed it, please try again.
