### ISSUE TITLE
Exported rst contains a lot: Inline literal start-string without end-string.

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#1186]
Current version of rst-export (dd 23rd may 2020), does not cleanly compile in Sphinx, giving errors like:

index.rst:941:Inline literal start-string without end-string.

It appears that a lot of items have a pipe-symbol ('|') prepended:

```
| When enabled, this option will treat label contents as HTML, and
| any FOREGROUND COLOR RELATED html formatting options will be
| respected in the rendered label.

| I repeat: ONLY HTML COLOR TAGS ARE RESPECTED. This is NOT a bug,
| rather this feature has been designed as a "test of the waters"
| with HTML formatting in labels, and accordingly only formatting
| options which do not alter the font shape were considered.
```

I have seen this before in earlier versions, but now it looks like a lot of items have it.

I'm not sure why some items have it and others not.

**Comment by anitanh** [comment]
hi @rduivenvoorde yes I found this too probably because they had github formatting, but the latest one doesn't have this because the entries has been converted into html when we download the remote images.
Nevertheless, if you find this problem again please let me know.

**Comment by rduivenvoorde** [comment]
@ann26 @timlinux ok I can do some tests today. Is this version already deployed on the live server? Or should I wait untill you give me a message?

**Comment by anitanh** [comment]
hi @rduivenvoorde yes it's already deployed on the live server
