### ISSUE TITLE
RST export: sphinx cannot hanlde space replacements?

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#1188]
Current version of rst-export (dd 23rd may 2020), does not cleanly compile in Sphinx, giving errors like:

index.rst:39:Undefined substitution referenced: "cumulative_animation_range".

Some images name seem to contain spaces, which are replace by '\_' or so?

Se below:

```
Adds a setting in temporal controller to set the animation temporal range as cumulative, that is all animation frames will have the same start date time but different end date time when the temporal range is cum

eg.
|cumulative\_animation\_range|

This feature was developed by `Samweli Mwakisambwe <https://api.github.com/users/Samweli>`__

.. |cumulative\_animation\_range| image:: https://user-images.githubusercontent.com/2663775/81475518-77cb4480-9215-11ea-96a6-78b93ca01a69.gif
```

**Comment by anitanh** [comment]
this issue has been handled in this PR: https://github.com/kartoza/prj.app/pull/1195. Since it removes the name of the image and so in RST it will has name like `|image1|` etc
