### ISSUE TITLE
RST export: it would be best if the export would contain the real images

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#1189]
In current export, people link there images to github images:

```
.. |image| image:: https://user-images.githubusercontent.com/127259/80964825-d0fc3800-8e11-11ea-9961-34edb623458c.png
```

But if we want to be able to independent of github, or if we want to be able to generate thumbnails ourselves, it would be best to download and save those images, so they will be available in the export (as they were earlier??).

I have been trying to get https://github.com/sphinx-contrib/images working but fail to do this if the images are on github. But please verify

**Comment by timlinux** [comment]
Any updates @ann26 ?

**Comment by anitanh** [comment]
@timlinux I made a PR here https://github.com/kartoza/prj.app/pull/1195

**Comment by timlinux** [comment]
Thanks!
