### ISSUE TITLE
strings in certificate mail include b'string'

### ISSUE THREAD

**Issue by mbernasocchi** [kartoza/projecta#1191]
I just sent myself a certificate to test the email and the dynamic strings in the email are shown with  a `b' '` prefix.
for example `dear b'Marco' b'Bernasocchi'`
![image](https://user-images.githubusercontent.com/233663/83113369-db83b780-a0c7-11ea-9677-12fe3f130dfa.png)

**Comment by anitanh** [comment]
hi @mbernasocchi I fixed it, please try again.
