### ISSUE TITLE
We lost the release menu

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#1193]
Since the CMS menu is added, we lost the one for the releases 

![image](https://user-images.githubusercontent.com/178003/83687871-56773180-a5e4-11ea-8195-40dfee00067d.png)

**Comment by anitanh** [comment]
hi @timlinux have you logged in? only staff or changelog managers can see the changelog menus
![Screenshot from 2020-06-08 10-50-39](https://user-images.githubusercontent.com/26101337/83991134-131b1b00-a976-11ea-95e1-696e8bf61852.png)
