### ISSUE TITLE
Save button is visible

### ISSUE THREAD

**Issue by Gustry** [kartoza/projecta#1202]
I was trying to create a organization on this page:
https://changelog.qgis.org/en/qgis/create-certifyingorganisation/

On my screen, zoom by default at 100%, I can't see the "Save" button.

![Screenshot from 2020-07-21 16-44-48](https://user-images.githubusercontent.com/1609292/88072230-14468700-cb75-11ea-888a-d7525c06b064.png)

Hopefully, by reducing the zoom to 80%, I could see the button, **which was previously hidden behind the footer** and I couldn't scroll more:

![Screenshot from 2020-07-21 17-13-54](https://user-images.githubusercontent.com/1609292/88072690-a3539f00-cb75-11ea-86b9-e3465d4c6979.png)

The button should be visible by default. My screen is not small.

Using Firefox 78.0.2 on Ubuntu 20.04

**Comment by anitanh** [comment]
hi @Gustry I've fixed it, please try again.
