### ISSUE TITLE
Import PR from Github, missing labels

### ISSUE THREAD

**Issue by Gustry** [kartoza/projecta#1215]
On http://changelog.lizmap.org, I'm trying to setup the auto-harvesting PR function from GitHub.

But it seems the list of labels is emtpy:
![Screenshot from 2020-09-28 10-20-48](https://user-images.githubusercontent.com/1609292/94408179-b89c0980-0174-11eb-8971-4be455bade8b.png)

So we have an error when trying to harvest. What can we do to have the list of labels?

Side question, I guess we need to tag every PR with a milestone named with the exact same name as the version in the changelog website.

**Comment by Gustry** [comment]
I have setup prj.app on my local machine here, setting up the github token and I could get the labels working.

I have also tried on https://changelog.qgis.org and the script could harvest labels from the Lizmap repository.

@timlinux Can you check that there is a token for GIT on changelog.lizmap.com ? It seems a different server than changelog.qgis.org.

From https://github.com/kartoza/prj.app/blob/develop/django_project/changes/views/changelog_github.py#L18..L21

```python
try:
    from core.settings.secret import GIT_TOKEN
except ImportError:
    GIT_TOKEN = ''
```

It will silently fail if there is not GIT token in the secrets.py.

**Comment by timlinux** [comment]
Hi 

Yes it is on a different server. @sumandari can you copy the token over from the changelog.qgis.org server to the instance on changelog.kartoza.com please?

**Comment by sumandari** [comment]
@timlinux  I have copied the GIT_TOKEN over from changelog.qgis.org server to changelog.kartoza.com server (core/settings/secret.py).

**Comment by Gustry** [comment]
I can confirm I can see labels now. Thanks!

I will let #1218 open as it's still needed to debug.
