### ISSUE TITLE
Add youtube links to module pages and pdf outputs

### ISSUE THREAD

**Issue by zacharlie** [kartoza/projecta#1232]
Lesson modules currently support the inclusion of a "youtube link", but do not include the link within the module contents or in the output pdf.

Ideally, this functionality should exhibit the following behaviour:

- [ ] For PDF outputs, the video link should be added to the top of the "Further reading" section and use the link description *module video tutorial*
- [ ] For web forms, the video should be embedded at the top of the module, directly below the module title and the summary leader element. Youtube API terms of service should be reviewed so that the implementation is compliant with their developer policies etc.

**Comment by sumandari** [comment]
Hi @zacharlie the fix #1242 has been deploy. Please kindly try it.
