### ISSUE TITLE
Add a "funded by" element to lessons

### ISSUE THREAD

**Issue by zacharlie** [kartoza/projecta#1233]
Add a "funded by" element, the same as which is available in the changelog entries, but for lesson modules.

**Comment by sumandari** [comment]
Hi @zacharlie, the fix #1253 has been deployed.

**Comment by zacharlie** [comment]
I can't seem to find how this value is modified.

**Comment by sumandari** [comment]
This element cannot be modified by author yet. Would you please explain should it be an input field so that the author can fill it in or it's a dropdown shows list of funder from the database?

**Comment by zacharlie** [comment]
I think an input field embedded directly on the edit page for each module is probably the best approach...

**Comment by sumandari** [comment]
The fix #1272 has been deployed on staging server.
