### ISSUE TITLE
Change object references

### ISSUE THREAD

**Issue by zacharlie** [kartoza/projecta#1237]
Some worksheet references display object references rather than meaningful content identifiers, such as ```Worksheet object (100)``` which can be viewed from answer sheets in section modules.

![image](https://user-images.githubusercontent.com/64078329/102830517-21042b00-43f2-11eb-8892-22e8417cefff.png)

Public example: https://changelog.kartoza.com/en/geonode/section/geonode-28/answers/28/

**Comment by sumandari** [comment]
@zacharlie the fix has been deployed. Please kindly check out the public example: https://changelog.kartoza.com/en/geonode/section/geonode-28/answers/28/
