### ISSUE TITLE
Add content license information

### ISSUE THREAD

**Issue by zacharlie** [kartoza/projecta#1238]
Course content should include a field for content license information. Ideally, this license information should be included with course resource downloads.

**Comment by sumandari** [comment]
Hi @zacharlie, could you explain about the field for content license information. Is it going to be a static field with license information (static html element) or it requires a new field in the model, so that the author can edit the license information?

**Comment by zacharlie** [comment]
The author should be able to edit it as course content and media could have different license implications. This is usually suitable as a simple text field and can be packaged with resources as a license.txt file

**Comment by sumandari** [comment]
@zacharlie the fix has been deployed. Can we close this issue now? Or is there anything should be improved?

**Comment by zacharlie** [comment]
Looks like this field is an empty drop down menu in the new deployment. How can we define license that can we apply to content?

**Comment by sumandari** [comment]
Author should create license from the admin site. Do we need to create the license from the web view?

**Comment by zacharlie** [comment]
I see. I have a few concerns, but I haven't got a better solution/ approach at the moment so this should be ok for now and I will have to think more on what changes we might implement.
