### ISSUE TITLE
Permalink to a feature is not working.

### ISSUE THREAD

**Issue by Gustry** [kartoza/projecta#124]
The permalink to a feature does not work. For instance ``http://changelog.linfiniti.com/qgis/version/2.10/#275`` does not scroll to the anchor.

Moreover,if we click on the anchor, the webbrowser doesn't keep the link.

**Comment by rischanlab** [comment]
Hi @timlinux @Gustry 
I've made PR for this bug https://github.com/kartoza/projecta/pull/135
It will work well. 

Thanks
