### ISSUE TITLE
Enable smarter download options

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/projecta#1243]
# Problem

Not all worksheets have data content. I suggest we only show the Download data options if the worksheets contain a zip file
![downsad](https://user-images.githubusercontent.com/2510900/102870185-5a19bb00-4445-11eb-9599-3e5c78287550.png)

Example https://changelog.kartoza.com/en/geonode/section/geonode-28/detail/108/?q=1.18

**Comment by zacharlie** [comment]
I would like to add that the behaviour for these links also needs to change and behave in a similar way to that described in #1232 and the review on #1242 

Currently, if a resource pack is available for the module an element is appended to the bottom of the content with the centere phrase ```Click <link>here</link> to download the sample data for the lesson.```

This is suitable for the web based/ digital content, but unsuitable for printed materials. When printed, users will not have any way to download this think.

Instead, I think for PDF outputs the resource link should be appended to the "Further reading" section (above the module video link) with the description "Module downloadable resources"

**Comment by NyakudyaA** [comment]
> I would like to add that the behaviour for these links also needs to change and behave in a similar way to that described in #1232 and the review on #1242
> 
> Currently, if a resource pack is available for the module an element is appended to the bottom of the content with the centere phrase `Click <link>here</link> to download the sample data for the lesson.`

Just to inherit the conversation from one PR in QGIS about using click `Here` https://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/
> 
> This is suitable for the web based/ digital content, but unsuitable for printed materials. When printed, users will not have any way to download this think.
> 
> Instead, I think for PDF outputs the resource link should be appended to the "Further reading" section (above the module video link) with the description "Module downloadable resources"

**Comment by sumandari** [comment]
The fix #1255 has been deployed on staging server.

**Comment by sumandari** [comment]
The fixed has been deployed, I will close this ticket now
