### ISSUE TITLE
Review strategy for worksheets

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/projecta#1245]
# Problem

The lesson app is great but we need a way to review exercises between ourselves or external content creators. 

The current scenario is 
* John writes an exercise sheet and saves it. Even before finishing it becomes available for everyone to see it.

# Proposed Solution 

* John writes an exercise. He should save it and continue editing until he feels it needs a review from someone else. Whilst he is editing his worksheet at any time it should never be visible on the site to the public users.
* Foo user then goes to the site and check which exercises need reviewing. Once he is happy with it he then published the worksheets. ( In the future if we have more contributors writing exercise we should have email notification to let a content reviewer that there is material to be reviewed)
* An Admin user can still write material and publish it without having anyone to review it.

cc @zacharlie 
**NB** We currently have to this process manually to indicate to one another that can review my work.

**Comment by zacharlie** [comment]
I think this seems like quite a technical challenge to implement the workflow you describe, so we should either discuss an alternative approach, and incremental implementation plan or a comprehensive workflow.

From my understanding you are proposing the following workflow:

Each worksheet has a "published" copy and a "draft" copy. When the edit button is pressed it navigates to the "draft" version.

We then need actions exposed for the following items:

- Approve Worksheet: copies the state from "draft" to the "published" object.
- Reset Worksheet: copies the state from "published" to the "draft" object.
- Request Review: Send email notification to reviewers. Each worksheet would need designated reviewer accounts which defaults to all content editors group, but can be modified to a specific user account or email address when the action is triggered.
- Preview: The application front-end only reads from the "published" object. When signed in as an editor, a "preview" option should be available for reviewing the rendered results from the "draft" copy. This should not be accessible by anonymous users. When editing the "draft" copy, saving the changes should default to the "Preview" page. The preview should include the export to PDF option as well.
- Review master: When on the preview page, editors should be able to quickly switch back to the master "published" object view

Ideally, If this intended for the long term with multiple contributors, I think this should be extended to the following:

The main worksheet state that is publicly viewable is retained as the master copy, which is made available after an approval/ review workflow (e.g. approved by a "content-admin" role).

An alternative, private, copy is retained as the latest "published" copy. If this get's approved it's state supersedes the master document. Until it get's given this approval, the review document is kept in a private state, and authors can request review from content administrators (group/ individuals) which sends email notifications.

I'm not sure whether this "review" copy should have a single instance, or a multi (per user) instance.

In addition, this assumes that each user account that initiates an editing session get's given their own "draft" copy of the worksheet object. This inherits it's state from either the current master or the current review document (depending on where the edit is initialised) and remains attached to the users content

"Admin" users should be able to submit their own drafts and review/ publish them automatically using this workflow anyway, it just becomes a multi-step process which is good for quality assurance purposes anyway.

This would probably also need some form of collision detection, or at least some form of indication that the original source document used to initiate the "draft" document state has changed (e.g. the master). This would probably require a UID for all worksheet object versions.

**Comment by NyakudyaA** [comment]
> I think this seems like quite a technical challenge to implement the workflow you describe, so we should either discuss an alternative approach, and incremental implementation plan or a comprehensive workflow.
> 
> From my understanding you are proposing the following workflow:
> 
> Each worksheet has a "published" copy and a "draft" copy. When the edit button is pressed it navigates to the "draft" version.

No. I am just suggesting that a worksheet should not be visible to the online world without someone approving it
Example:
![example-work](https://user-images.githubusercontent.com/2510900/102891069-492d7180-4466-11eb-9bf7-9b4837374a03.png)

The above sheet is visible to anyone navigating to changelog.kartoza. If we had a flag that would just tag this as unfinished until I finish populating it. When I am done populating it I can just ping you and then you review the content and then when you happy you tag it as completed

In geoserver we have something like this

![adv](https://user-images.githubusercontent.com/2510900/102891414-d07ae500-4466-11eb-8a73-41ff3facef99.png)

A resource that is not advertised is not visible to the outside world

> 
> We then need actions exposed for the following items:
> 
>     * Approve Worksheet: copies the state from "draft" to the "published" object.
> 
>     * Reset Worksheet: copies the state from "published" to the "draft" object.
> 
>     * Request Review: Send email notification to reviewers. Each worksheet would need designated reviewer accounts which defaults to all content editors group, but can be modified to a specific user account or email address when the action is triggered.
> 
>     * Preview: The application front-end only reads from the "published" object. When signed in as an editor, a "preview" option should be available for reviewing the rendered results from the "draft" copy. This should not be accessible by anonymous users. When editing the "draft" copy, saving the changes should default to the "Preview" page. The preview should include the export to PDF option as well.
> 
>     * Review master: When on the preview page, editors should be able to quickly switch back to the master "published" object view
> 
> 
> Ideally, If this intended for the long term with multiple contributors, I think this should be extended to the following:
> 
> The main worksheet state that is publicly viewable is retained as the master copy, which is made available after an approval/ review workflow (e.g. approved by a "content-admin" role).
> 
> An alternative, private, copy is retained as the latest "published" copy. If this get's approved it's state supersedes the master document. Until it get's given this approval, the review document is kept in a private state, and authors can request review from content administrators (group/ individuals) which sends email notifications.
> 
> I'm not sure whether this "review" copy should have a single instance, or a multi (per user) instance.
> 
> In addition, this assumes that each user account that initiates an editing session get's given their own "draft" copy of the worksheet object. This inherits it's state from either the current master or the current review document (depending on where the edit is initialised) and remains attached to the users content
> 
> "Admin" users should be able to submit their own drafts and review/ publish them automatically using this workflow anyway, it just becomes a multi-step process which is good for quality assurance purposes anyway.
> 
> This would probably also need some form of collision detection, or at least some form of indication that the original source document used to initiate the "draft" document state has changed (e.g. the master). This would probably require a UID for all worksheet object versions.

**Comment by zacharlie** [comment]
So basically just an option that toggles the worksheets publicly visible state (it will always be available to editors)?

This may present UX issues when users are reviewing content and the available modules and the available worksheet numbers are ```1.1, 1.2, 1.3, 1.5, 1.9```, but to be fair only one existing worksheet should be getting edited at a time, and provides a good solution for "not yet published" articles. It's a suitable band-aid IMO

**Comment by NyakudyaA** [comment]
> So basically just an option that toggles the worksheets publicly visible state (it will always be available to editors)?

Yes, the editing workflow and approval can come in at a later stage. This might require a big architecture change i.e models, sending emails, setting up groups and roles as you have outlined above.
> 
> This may present UX issues when users are reviewing content and the available modules and the available worksheet numbers are `1.1, 1.2, 1.3, 1.5, 1.9`, but to be fair only one existing worksheet should be getting edited at a time, and provides a good solution for "not yet published" articles. It's a suitable band-aid IMO

This can be fixed by disabling `Order Section` for an unpublished worksheet. Adding a worksheet already makes it the last sheet by default.

**Comment by sumandari** [comment]
@NyakudyaA @zacharlie is it important to keep the same numbering on admin/project owner and normal user. Please have a look at the image. Left side is admin/project owner view, right side is normal user/anonym view.

![image](https://user-images.githubusercontent.com/40058076/104565615-7943eb00-5687-11eb-9e79-1d3d58eba9e5.png)

**Comment by zacharlie** [comment]
The process you have outlined in the screenshot above is perfect IMO 👍 🥇

**Comment by sumandari** [comment]
So can you confirm that the different numbering on admin view and normal user view is fine? @zacharlie

**Comment by zacharlie** [comment]
I'm happy with it. Maybe get confirmation from @NyakudyaA or @timlinux before implementing

**Comment by NyakudyaA** [comment]
@sumandari That looks great. Just a quick question. What happens if the draft worksheet is now approved. Does the numbering change in the normal view?

**Comment by sumandari** [comment]
yes @NyakudyaA. The numbering will change in the normal view. The numbering is set on the frontend, it comes from looping index of the worksheet object.

![image](https://user-images.githubusercontent.com/40058076/104583313-f4170100-569b-11eb-81cc-a06dc7cb3686.png)

**Comment by sumandari** [comment]
The fixed has been deployed, I will close this ticket now
