### ISSUE TITLE
Text in PDF are not rendered properly

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/projecta#1246]
On-site

![site-a](https://user-images.githubusercontent.com/2510900/102887432-9fe37d00-445f-11eb-8a5b-00f82faaa774.png)

Downloaded PDF

![down-pdf](https://user-images.githubusercontent.com/2510900/102887465-b4277a00-445f-11eb-903a-f9cfac986d4a.png)

**Comment by zacharlie** [comment]
I have been going through and manually replacing these characters in the content and using the ```'``` character on my windows system doesn't seem to have these errors. Manual fix is still a work around though so I definitely think this should be prioritised.

**Comment by NyakudyaA** [comment]
I think some of this is because the worksheets initially were written in libre office and someone had to copy-paste the content from the libre office docs to the web.

**Comment by sumandari** [comment]
@NyakudyaA the fix has been deployed. Please check out the example case:
https://changelog.kartoza.com/en/geonode/section/geonode-28/print/111/?q=1.2.1
Can we close the issue now?
