### ISSUE TITLE
Allow changing worksheet order from front end

### ISSUE THREAD

**Issue by zacharlie** [kartoza/projecta#1248]
Currently worksheet numbers seem to be statically assigned. Allowing editors to reshuffle the worksheet (and section) order from the frontend and have the worksheet numbers change dynamically will be very beneficial for maintenance and course structuring. Attempting this from the django admin is dangerous IMO and could lead to unexpected results.

**Comment by NyakudyaA** [comment]
![order-groups](https://user-images.githubusercontent.com/2510900/102894383-ad9eff80-446b-11eb-9ae4-b702b8300228.png)

Doesn't this work for you?

**Comment by zacharlie** [comment]
I had tried it before and it didn't work. Maybe it was back before the migration. I should have checked again before posting this one. Sorry for the noise.
