### ISSUE TITLE
Add "lessons" route

### ISSUE THREAD

**Issue by zacharlie** [kartoza/projecta#1249]
I think the URL path for the lessons app should be more apparent. For example, ```https://changelog.kartoza.com/en/geonode/lessons/``` looks better than ```https://changelog.kartoza.com/en/geonode/section/list/```. Even a redirect is suitable for current purposes.

**Comment by sumandari** [comment]
@zacharlie the fix #1256 has been deployed on staging server.

**Comment by sumandari** [comment]
The fixed has been deployed, I will close this ticket now
