### ISSUE TITLE
Fix module number error after editing lesson content

### ISSUE THREAD

**Issue by zacharlie** [kartoza/projecta#1257]
If a lesson is edited and saved, the page does not show the module numbers in the html or pdf.

![image](https://user-images.githubusercontent.com/64078329/103202300-b4f65b00-48fa-11eb-97b4-f562c4719a54.png)

Refreshing the page does not fix it, but navigating back to the module list and returning to the same module updates these values. This should happen automatically.

**Comment by sumandari** [comment]
Hi @zacharlie, the fix #1275 has been deployed on staging server.
