### ISSUE TITLE
Incorrect path for automatically harvested changelog media

### ISSUE THREAD

**Issue by zacharlie** [kartoza/projecta#1282]
When the "Import PR from GitHub" tool is used to collect data from GitHub, the tool automatically collects some media items and attempts to attach the media as a file, but this results in the incorrect path being generated. As an example, the file `https://changelog.qgis.org/media/media/images/entries/95669631-e0b24200-0b50-11eb-9efe-2c227def9190.gif` does not resolve correctly due to the duplication of `media/` in the path, but the media is available from `https://changelog.qgis.org/media/images/entries/95669631-e0b24200-0b50-11eb-9efe-2c227def9190.gif`

**Comment by sumandari** [comment]
The fix has been deployed. I will close this for now
