### ISSUE TITLE
[Certification] Issue with second certificate to the same e-mail address

### ISSUE THREAD

**Issue by gis-support** [kartoza/projecta#1288]
Hello,

We experience an issue when creating a second QGIS certificate for the same person.

Scenario:
1. Issue a certificate for person X for the "QGIS basics".
2. Try to issue a certificate for person X with the same e-mail address, but for "QGIS advanced".

Screenshot:
![certificate_isssue](https://user-images.githubusercontent.com/10209250/105166658-f522b500-5b17-11eb-9519-50e87b504e48.png)

We kindly ask you to allow the issuing of certificates for the same people (with the same e-mail), but at different levels of QGIS courses.

**Comment by sumandari** [comment]
Hi @gis-support, 

Please apologies for long delay.

For issuing certificate for the same person, would you please try these following steps:

#### 1. Click on **Add Course Attendee** button
  
![image](https://user-images.githubusercontent.com/40058076/107493161-47f80580-6bc8-11eb-972c-b77260dc7518.png)

#### 2. Select the attendee from select input, and click on submit button
  
![image](https://user-images.githubusercontent.com/40058076/107493351-7675e080-6bc8-11eb-939f-6017959c4200.png)

#### 3. The same attendee will be added in the table list.
  
![image](https://user-images.githubusercontent.com/40058076/107493525-ad4bf680-6bc8-11eb-857b-967a962dbd22.png)


---

#### gif animation for the steps above

![changelog_1288_attendee](https://user-images.githubusercontent.com/40058076/107492713-ba1c1a80-6bc7-11eb-928a-714995202419.gif)

#### Issuing certificates

![image](https://user-images.githubusercontent.com/40058076/107494915-5515f400-6bca-11eb-951a-721c7b1fc03c.png)

![image](https://user-images.githubusercontent.com/40058076/107494954-652dd380-6bca-11eb-9487-aa755774e9e1.png)


Hope this information will resolve your issue. Please let us know when the issue still exists. Thank you.
