### ISSUE TITLE
Allow option to highlight correct answers for webview exercise

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/projecta#1292]
# Problem

When I am doing the lessons I cannot determine which is the correct answer to a question.
![answer](https://user-images.githubusercontent.com/2510900/106864448-8c6c3880-66d2-11eb-9a22-4029483a89a5.png)

# Solution

Highlight the correct answer when a user hovers or clicks on the answer. Alternatively, you can add the option for the user to submit the answers and then show the correct answer

**Comment by christopherbuirski** [comment]
![Solution ](https://user-images.githubusercontent.com/78072657/106900273-00bcd100-66ff-11eb-9fad-78d39519f8b1.jpg)

**Comment by sumandari** [comment]
The fixed has been deployed, I will close this ticket now
