### ISSUE TITLE
Module 1.4 lesson. "Create Layer" option in "Data Menu" on geonode training not visible 

### ISSUE THREAD

**Issue by christopherbuirski** [kartoza/projecta#1293]
In the lesson it had these instructions: 
<img width="648" alt="Screenshot 2021-02-05 at 9 25 29 AM" src="https://user-images.githubusercontent.com/78072657/107005494-745eec80-6798-11eb-898c-68c913eb3cf2.png">

On geonode it doesn't have the option to create a layer 
<img width="480" alt="Screenshot 2021-02-04 at 4 57 42 PM" src="https://user-images.githubusercontent.com/78072657/107005508-7b85fa80-6798-11eb-94eb-ac5e8031a170.png">

**Comment by NyakudyaA** [comment]
@christopherbuirski This just needs to be activated only.  Have notified @lucernae
