### ISSUE TITLE
Stab in the dark to get other sections

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/projecta#1296]
# Problem

When writing lessons, it looks like a stab in the dark to find other sections i.e `Further Reading`, `New Requirements`

![stab-in](https://user-images.githubusercontent.com/2510900/107637225-746a5b00-6c76-11eb-8df4-8915948e35ce.png)

How can we make these sections become more prominent so that they are visual. I know if you hover over somewhere they show up. 

But if we have other users writing lessons do we expect them to guess that they are other sections

cc @zacharlie

**Comment by sumandari** [comment]
The fix has been deployed. I will close this now.
