### ISSUE TITLE
Add project management tool to enable / disable functions

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#1303]
Some projects don't have teams, lessons etc.

![image](https://user-images.githubusercontent.com/178003/108342208-71212300-71d2-11eb-9a49-a5c243c79810.png)

Can you make in the project management page e.g. at https://changelog.qgis.org/en/project/qfield/update/

I would imagine a section on the project editing page with checkboxes like this:

- [ ] Enable Lessons
- [ ] Enable Sustaining Members
- [ ] Enable Teams
- [ ] Enable Changelogs
- [ ] Enable Certification

If a module is unchecked, its block should be hidden on the landing page and also any related menu entries removed.

**Comment by sumandari** [comment]
The fixed has been deployed. I will close this now.
