### ISSUE TITLE
Generated rst image issue 1

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#1304]
Downloading the rst for 3.18:

there are 9 images which do not have a source. At the bottom of the rst they look like "image5" here below:

.. |image4| image:: images/entries/5adbd9ce0bfeb73ec308ed003603aacceab728d4.png
   :class: img-responsive img-rounded
.. |image5| image::·
.. |image6| image:: images/entries/24c8af6d1314e7a22f8f70a7628f3aeae9b3ce1a-1.png

Not sure what the reason is they are empty, but at the moment I can only remove both the images and the references to make it build.

Seems fixable

**Comment by timlinux** [comment]
Thanks @rduivenvoorde @sumandari will you take a look please? The incoming issues from @rduivenvoorde are time critcal as we need to get the release announcements out on time.

**Comment by rduivenvoorde** [comment]
@sumandari am I right that this is not yet fixed? Because this issue is mentioned in #1306 I thought it was, but  I just downloaded the rest zip and still found 'empty' image uries:

```
.. |image32| image:: images/entries/0dad8d8307a3c3fe1f5b28aa56790b307c090f33-1.gif
   :class: img-responsive img-rounded
.. |image33| image::                                         <== THIS ONE I MEAN 
.. |image34| image:: images/entries/9a48f9d2970e50c7d4f70358b6cfd870033427a5-1.gif
```

This issue is actually more severe then #1305, because I have no other way then remove these images I think...?

**Comment by sumandari** [comment]
@rduivenvoorde 
 oh, I see it now. I will look into it. I am sorry for mentioned it in #1306. I thought it was same.

**Comment by sumandari** [comment]
@rduivenvoorde 

The fix deployed. Would you please try it. Thank you.

/cc @dimasciput @timlinux 

![image](https://user-images.githubusercontent.com/40058076/108523683-2ce46e80-7309-11eb-9e3e-3d15d0e83cc7.png)

**Comment by rduivenvoorde** [comment]
@sumandari thanks! Works (see qgis website :-) )
