### ISSUE TITLE
Author links point to api github page

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#1309]
Just found out, both on changelog.qgis.org, as in qgis site, the author links in the website point to github api json output, eg:

https://api.github.com/users/rduivenvoorde

Is that deliberate? Or should we let it point to the repo url, or the list of qgis commits?

**Comment by sumandari** [comment]
@rduivenvoorde do we need to replace the existing value in website to the expected one?

**Comment by rduivenvoorde** [comment]
@sumandari I'll wait and see if others do fixes. Then my planning is to redo the download and then also push the texts to transifex. So: if the links are fixed in the rst download that is sufficient. Thanks!

**Comment by rduivenvoorde** [comment]
@sumandari maybe I misunderstood, will the links change, OR will they stay as they currently are (to api.github.com)...?

**Comment by sumandari** [comment]
@rduivenvoorde #1310 will point url to developer github repo. 
I was asking if we need management command to replace the existing value (api.github.com) to http://github.com/....

**Comment by sumandari** [comment]
The fixed has been deployed. I will close this for now
