### ISSUE TITLE
Download rst zip currently fails

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#1315]
Trying to download the rst zip fails currently, both in browser on via cli:

```
$ wget https://changelog.qgis.org/en/qgis/version/3.18/download/
--2021-02-23 13:21:38--  https://changelog.qgis.org/en/qgis/version/3.18/download/
Resolving changelog.qgis.org (changelog.qgis.org)... 78.46.204.5
Connecting to changelog.qgis.org (changelog.qgis.org)|78.46.204.5|:443... connected.
HTTP request sent, awaiting response... 410 Gone
2021-02-23 13:21:38 ERROR 410: Gone.
```

**Comment by rduivenvoorde** [comment]
@sumandari @timlinux is there something in the logs? Looks like it starts and then stops, as the html download is doing fine...
I know Andreas added the large table with all the 'notable commits'....  maybe that breaks the rst generation?

**Comment by sumandari** [comment]
@rduivenvoorde it's low disk space issue and has been fixed temporary. The download should work fine now. I will ask @timlinux to add the storage space.

/cc @dimasciput

**Comment by rduivenvoorde** [comment]
@sumandari thanks! Fixed and used to create new index.rst for website
