### ISSUE TITLE
Fix GitHub Import

### ISSUE THREAD

**Issue by sumandari** [kartoza/projecta#1317]
Can you also fix the GitHub importer so that when the images are initially imported they are correct?

_Originally posted by @timlinux in https://github.com/kartoza/prj.app/issues/1306#issuecomment-782080750_

**Comment by Gustry** [comment]
Duplicate of https://github.com/kartoza/prj.app/issues/1230 ?

**Comment by sumandari** [comment]
@Gustry this is to avoid/fix issue #1304 and #1305.
And yes, #1305 is duplicate of #1230. Thank you for pointing it out.

**Comment by sumandari** [comment]
The fixed has been deployed, I will close this ticket now
