### ISSUE TITLE
Unable to upload images, data for exercises on changelog.kartoza

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/projecta#1321]
# Problem

* Navigate to https://changelog.kartoza.com/en/geonode/lesson/geonode-28/detail/191/?q=1.25
* On the exercise image try to add an image exercise and then save.
* You will encounter an error
![error-change](https://user-images.githubusercontent.com/2510900/111590584-f34f3800-87ce-11eb-916c-bad2e243afda.png)

This also happens randomly when adding text, data

**Comment by sumandari** [comment]
@NyakudyaA this error 500 doesn't occur anymore on https://changelog.kartoza.com/en/geonode/lesson/geonode-28/detail/191/?q=1.25. I'm not sure why, will check the sentry error log once got the access.

**Comment by NyakudyaA** [comment]
This doesn't happen anymore. Will open again if need arises
