### ISSUE TITLE
Simplify sample data export formats

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/projecta#1328]
# Problem

Currently, if a user downloads sample data from a worksheet i.e
![sample-data-work](https://user-images.githubusercontent.com/2510900/113674037-019bc000-96ba-11eb-9b28-53cd6dcd11fd.png)

And then unzip the file produces a file structure that is two folders deep. 
ie. 

It seems like after uploading the sample data as a zip file, it is further zipped again.

# Solution

If we need to standardize the name of the zip file let us rather rename a zip file that is uploaded rather than zip a zip file.
What is the benefit of zipping twice?

**Comment by sumandari** [comment]
@NyakudyaA is this duplicate with #1337 ?

**Comment by NyakudyaA** [comment]
Yes @sumandari in fact Tim's ticket is the duplicate as I wrote this earlier than him but we can close this 🙂🙂🙂

**Comment by sumandari** [comment]
@NyakudyaA I submitted #1341 
It's unzipping file when author uploaded sample data with zip in zip.
Please confirm if it's not necessary, I will close it then.

**Comment by NyakudyaA** [comment]
I will look at the PR and comment

**Comment by sumandari** [comment]
The fix has been released in v2.3.0 and deployed on prod.
