### ISSUE TITLE
PDF outputs should not include none in final output

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/projecta#1334]
# Problem

Whenever an expectation box contains null values or actually data is is always printed with the text `None`. We should avoid this situation as it is confusing for the people.

![Screenshot 2021-04-28 at 15 50 49](https://user-images.githubusercontent.com/2510900/116415532-cd8b6900-a839-11eb-9569-3a44c4fad8a1.png)

In this case above None should never have been printed in the sheets

**Comment by sumandari** [comment]
The fixed has been deployed, I will close this ticket now
