### ISSUE TITLE
Add Download PDF and Data all in one button in worksheet

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#1337]
On the lessons list we have this button to download the lesson pdf and data in one zip

![image](https://user-images.githubusercontent.com/178003/116856986-f32ac080-abf3-11eb-9199-ae922c681959.png)

Can we have the same button shown at the top of the worksheet too:

![image](https://user-images.githubusercontent.com/178003/116857075-19e8f700-abf4-11eb-9412-93e353f222e2.png)

Also when the worksheet + data zip downloads, it has another zip inside it with the data. Can you please unpack that so that the user does not need to unzip the first zip then go inside and unzip the second?

**Comment by sumandari** [comment]
The fixed has been deployed, I will close this ticket now
