### ISSUE TITLE
Build fails because of: Duplicate substitution definition name: "image".

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#1348]
Testing rst export for QGIS 3.20.

```
Warning, treated as error:
./source/site/forusers/visualchangelog320/index.rst:754:Duplicate substitution definition name: "image".
make: *** [Makefile:116: html] Error 2
```

While easy fixable in the rest source (it's just rename a couple of lines/names), I thought to let you know that apparently the 'automatic naming' is failing (note the 3x 'image' name), not sure why:

```
.. |image| image:: https://changelog.qgis.orgimages/entries/f0cad8bbc2de6c44b22c4875c45ed6e24e9f4bf6.png
.. |image13| image:: images/entries/14f48f5bcc891d1c97a8b187f53bb21c6dd6dff6.png
   :class: img-responsive img-rounded
.. |image| image:: https://changelog.qgis.orgimages/entries/44767fa890705c09d9c4b21b998807c7999ddde4.gif
.. |image| image:: https://changelog.qgis.orgimages/entries/3a408fbcff1ee8d5889c3fe30c0d9d831b050698.gif
.. |image16| image:: images/entries/be73e288ed1f46860868a6ae49e7d1f8604082b9.png
   :class: img-responsive img-rounded
.. |image17| image:: images/entries/3b34a6b8ceb5cad5a423a10562511457c0c21396.png
```

After manually fixing those, the rest export builds fine! Thanks!

**Comment by sumandari** [comment]
Thank you for the report @rduivenvoorde 
This issue has been address in #1318 

I apologise for the inconvenience and the delay, we will deploy soon after the review done.

**Comment by rduivenvoorde** [comment]
Thanks, for the quick fix! Plz ping me when deployed, then I will test.

As said it is a small issue, even without deploying I'm happy to use current version or release of 3.20.

**Comment by sumandari** [comment]
@rduivenvoorde the fix has been deployed on changelog.qgis.org and changelog.kartoza.com - version 2.1.6.

**Comment by sumandari** [comment]
I will close this for now
