### ISSUE TITLE
Address stripe error 

### ISSUE THREAD

**Issue by sumandari** [kartoza/projecta#1352]
Please see: http://sentry.kartoza.com/sentry/projecta/issues/2898/

**Comment by sumandari** [comment]
test comment

**Comment by sumandari** [comment]
I have tested on local using test key `pk_test_` and `sk_test_` and it works well with `STRIPE_LIVE_MODE` = False

The issue was probably caused by Stripe's error connection:
```
"data": {
    "object": {
      "id": "ch_1J5M1fBBMqjyXePieRnTZh25",
      "object": "charge",
      "amount": 1000,
      "amount_capt…', "valid" = True, "processed" = False, "exception" = 'Unexpected error communicating with Stripe.  If this problem persists,
let us know at support@stripe.com.
```

**Comment by dimasciput** [comment]
Ok thanks @sumandari, will close this for now.
