### ISSUE TITLE
[Feature Request] Allow rephrasing of standard certificate sentences

### ISSUE THREAD

**Issue by andremano** [kartoza/projecta#1371]
The default wording certificates come with can be potentially incompatible with the internal procedures and regulations of academic (or other) institutions. In the example below, it would be easier internally if the wording could be changed to _Has attended the course_ intead of the current _Has attended and completed the course_.
![image](https://user-images.githubusercontent.com/6665872/140524560-3e7c36b4-f809-4630-9b76-7b9dd71222b2.png)

Adding the possibility of changing some of the default wording solves the issue. In order to avoid the risk of making the certificates too unstandardized it might be a bad idea to just leave it totally customizable. Therefore, I suggest that each these sentences are added to a list from where to choose from if (A) a request with a the specific sentence comes from a certifying organization (like in this concrete case) and (B)  the wording is approved by the QGIS certification program team.

**Comment by jvdkwast** [comment]
Indeed different certificate types are used. In my work I only see "Certificate of Attendance" and "Certificate of Completion". I don't know if there are other ones. But having a list also has my preference instead of a free field.

**Comment by andremano** [comment]
Thank you for your feedback @jvdkwast. @sumandari Is my suggestion something that can be implemented?

**Comment by sumandari** [comment]
Thank you for your input @andremano @jvdkwast. Regarding implementation in the code, yes, I think we can put a dropdown list to choose the certificate type in the course.
From @jvdkwast, we have got "Certificate of Attendance" and "Certificate of Completion" as option in the list. And possibly we will add (if there's any) another type in the future.
Would you please suggest how to propose **the wording** (or ask suggestion) to QGIS certification program team?
cc @timlinux

**Comment by andremano** [comment]
In addition to the cerrificate type (Certificate of attendance OR Certificate of Completion), my suggestion is for now to also add a dropdown list with two wording options:

1 - Has attended and completed the course (the current default)
2 Has attended the course

**Comment by timlinux** [comment]
# Part 1

Create a new model for certification course types and an admin page for creating / deleting types

# Part 2

In the certification menu add a place for certification managers to manage the list of certificate types. Only certification managers can see  this menu.

![image](https://user-images.githubusercontent.com/178003/142606678-54386909-acd7-474c-b884-969f6a103961.png)



# Part 3

Setting the attendance type on teh course: https://changelog.qgis.org/en/qgis/certifyingorganisation/qgis-kartoza-pty-ltd/course/qgis_introduction-qgis-online_2021-08-02-2021-08-04/update/

![image](https://user-images.githubusercontent.com/178003/142605462-0dd3e430-49f8-4c54-84f8-399812723d5a.png)

Can default to existing wording so previously created courses use the same wording

# Part 4

Update the template to get the certification type text from the course model

**Comment by andremano** [comment]
Thanks @timlinux - What you describe is pretty much what I had in mind when I opened this issue.

**Comment by andremano** [comment]
Poking this issue - I take it from the discussion that these changes have a green light and will be implemented?

**Comment by sumandari** [comment]
@andremano  This feature has been fixed in v2.3.0 and deployed on prod. I will close it for now

**Comment by andremano** [comment]
Thank you for this! Really appreciate it. Now, I assume that in order to add the terminology option `has attended`, I first have to request it to be listed and approved by @jvdkwast ? Is it so?

**Comment by sumandari** [comment]
For adding the Certificate Type with wording `has attended`, the admin can add the instance in admin page:
![image](https://user-images.githubusercontent.com/40058076/154383420-44f44fb6-b2c0-44d9-a715-8fa3fb956ecc.png)

![image](https://user-images.githubusercontent.com/40058076/154383468-ec44d932-1435-44f3-8d78-bd7f322b9404.png)

For adding the Certificate Type in a project, the Certification Manager can go to `Manage Certificate Type` in `Certification` menu and check the checkbox to choose
![image](https://user-images.githubusercontent.com/40058076/154383765-8f8c6206-0643-484a-83ce-477d0672639d.png)

I will re-open the ticket for the `has attended` certificate wording implementation in the platform

cc @timlinux @dimasciput

**Comment by andremano** [comment]
Thanks, @sumandari. I think having an admin approve/add a terminology first is a wise approach in order not to lose certificate consistency.  I will wait then for an admin to do it.

**Comment by andremano** [comment]
@jvdkwast could you please add the 'Has attended' to the list of allowed terminologies?

**Comment by jvdkwast** [comment]
@andremano This is a task for the developers. I'm not able to edit the list. @sumandari

**Comment by sumandari** [comment]
@andremano @jvdkwast I have added 'Has attended' in Certificate Type model. 
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/40058076/156390841-3e6c5e1b-d7c2-499a-88c0-d68626c167e1.png">
Now the Certification Managers can apply this certificate type into the project by checking the checkbox and clicking on the Save button.
@jvdkwast would you please check if you can check and save the Certificate Type in Certification >> Manage Certificate Type? Thank you

**Comment by jvdkwast** [comment]
@sumandari Yes that works.

**Comment by jvdkwast** [comment]
Thanks. Just a few questions:
So in this case for example @andremano is the Certification Manager and can change the settings for his organisation here by himself?
And for adding other Certification Types to the list we can contact the developers, right?

**Comment by sumandari** [comment]
Yes, If @andremano is the Certification Manager, he can change the Certificaye Type for the project. 
Later on, the Certifying Organisation can choose the type of the certificate for their courses in their settings. 
To add new Certificate Type, we can contact admin/ super user account to add via django admin page.

**Comment by andremano** [comment]
@Sumandri, I cant seem to be able to add a new certificate type. Apparently, I am the owner of the organization but I am not the certification manager - I don't see where I can assign that role to myself. I am sorry for keeping this thread so long

**Comment by andremano** [comment]
@sumandari I am sorry to keep extending this thread, but I am very confused about what I have to do. I do not have access to a 'Certificate type' menu unless I type to URL directly, but there, if I check the 'Has attended' option nothing happens. I guess this happens because I am the organization owner but not a 'Certification Manager'. How do I assign that role to myself?

**Comment by sumandari** [comment]
@andremano if you are not a Certification Manager so you should not be able to update the certificate type list, but you can update your certification type in your course. You are not supposed to be able to access the URL as well if you are not a Certification Manager. I will create a ticket to fix this.
Once a new Certificate Type has been added in a project (in this case is QGIS), all QGIS courses will have the new Certificate Type in `Certificate type*` drop-down input.

Please go to your course, create or edit course. 
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/40058076/156387278-f1b6ac99-bf8c-4e3b-82c2-f20ae5f0686e.png">

<img width="884" alt="image" src="https://user-images.githubusercontent.com/40058076/156387800-a034a91f-8806-4c51-ad8a-f236b59f07b2.png">

To update the wording in existing generated PDF, please re-generate PDF:

<img width="604" alt="image" src="https://user-images.githubusercontent.com/40058076/156389742-e03c2909-0f5b-48c8-80a4-2d696a8dc7ee.png">

ps. I saw earlier that the Certificate Type for `Has attended` hasn't been checked yet, so I checked it to enable this certificate type in QGIS courses. cc @jvdkwast @timlinux

**Comment by andremano** [comment]
@sumandari Ah yes! I see it now. Thank you so much for supporting this. I am sorry for having dragged you into this long thread @jvdkwast.
