### ISSUE TITLE
Cannot replace sustaining member logo

### ISSUE THREAD

**Issue by andreasneumann** [kartoza/projecta#1372]
I am trying to replace the already existing logo from sustaining member "Automatic knowledge" (https://changelog.qgis.org/en/qgis/member/dvtftt/update/) with a new version - but every time I try to replace this particular logo, I get a 500 webserver error.

Is there something special with this particular entry?

Thank you for your help!

**Comment by sumandari** [comment]
Hi @andreasneumann thank you for your report. 
From the sentry error, it found that your email address is not valid. Please kindly check your email domain in `Contact Email`. It probably needs to be updated.

And I think we should display the ValidationError on the web instead of return 500. I will look into this

**Comment by andreasneumann** [comment]
Strange - If I go to my projecta account settings, everything looks normal

![image](https://user-images.githubusercontent.com/884476/141763498-24565463-9663-4b6b-9ed5-91b0cf93980b.png)

**Comment by sumandari** [comment]
I meant the contact email in the `Update Sustaining Member for QGIS` page (https://changelog.qgis.org/en/qgis/member/dvtftt/update/):
![image](https://user-images.githubusercontent.com/40058076/141764014-4fd02fc2-dba8-4041-8e68-91bb9681f236.png)

**Comment by andreasneumann** [comment]
Ah - yes. After fixing the invalid e-mail I was able to replace the logo.

Thanks for your help!

**Comment by sumandari** [comment]
Cool!
And thanks again for your valuable report. It helps us improve the platform.

**Comment by sumandari** [comment]
The fix has been released in v2.3.0 and deployed on prod.
