### ISSUE TITLE
Certification review process updates

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#1377]
![image](https://user-images.githubusercontent.com/178003/144029290-acd55cca-6f1e-4f74-aa19-40b58f451b42.png)

- [ ] Convert current page to a simple non paginated list,
List columns would be
Org Name (hyperlink to org detai page), application date, application status

- [ ] Have table sortable by any column
- [ ] Move review buttons to detail page
- [ ] Clicking on an org will take you to detail page 
- [ ] The org list should be searchable

**Comment by sumandari** [comment]
This is also mentioned in #1379  step no.2
