### ISSUE TITLE
Top up credits for QGIS

### ISSUE THREAD

**Issue by careyshan** [kartoza/projecta#1401]
Hi Folks,

When I go to topup credits for QGIS, I am unable to. 

I get the following:

![image](https://user-images.githubusercontent.com/3117142/156237956-28af99cb-8e18-4ccb-8084-7cb926d81b2d.png)

and to "Pay With Stripe" is disabled. Could someone check it out for me please.

Thanks

**Comment by dimasciput** [comment]
Hi @careyshan , can you send me the link to this page please? Thanks.

**Comment by careyshan** [comment]
Hi @dimasciput,
Thanks for look at this. The link is: 
https://changelog.qgis.org/en/qgis/certifyingorganisation/maptech-solutions/top-up/
Cheers

**Comment by dimasciput** [comment]
@careyshan I tested in chrome and it's working, what browser did you use?

**Comment by careyshan** [comment]
Ah, @dimasciput, I was using firefox. I'll try chrome.
Cheers

**Comment by careyshan** [comment]
Hi @dimasciput, I've tried with chrome and not working in it for me either.

Cheers

**Comment by careyshan** [comment]
Hey @dimasciput, Just wondering have you had any joy with this? Thanks for your help

**Comment by dimasciput** [comment]
@careyshan I have fixed the bug with the up and down button, I'm closing this ticket.
