### ISSUE TITLE
Error 500 when trying to buy credits

### ISSUE THREAD

**Issue by andremano** [kartoza/projecta#1407]
When trying to buy credits, I get an error 500 message (tried on Chrome and Edge):

error id: **ebd66d588563427c923b3328481ad7d4**

In case it is relevant: attempting to buy 100 credits with a MasterCard credit card.

**Comment by zacharlie** [comment]
This appears to have been resolved by #1409

**Comment by andremano** [comment]
Yes, I confirm - it has been resolved. Forgot to update this thread, sorry.

**Comment by zacharlie** [comment]
You and me both., no need to apologise! And thanks again for raising this 😄
