### ISSUE TITLE
The web site https://changelog.qgis.org/ is not working

### ISSUE THREAD

**Issue by RobiFag** [kartoza/projecta#1428]
Hi all,
today I'm not able to log in to my organisation (gter) page using my github profile. When I try to log in I get this error:
_

> 400
> Erm....
> It looks like you might be trying to do something you're not allowed to.
> If this is not the case, try logging in. If you are already logged in, then you probably do not have permission. Sorry.

_

Previously I was able to log in correctly but when I tried to do any operation (e.g. create a new course or view the certificate preview) I got error 500

is there any problem with the site?

Thanks!

**Comment by dimasciput** [comment]
Hi @RobiFag can you check it again now? I did some fixes in the backend, please let me know if that resolved your issues.

**Comment by RobiFag** [comment]
Hi @dimasciput thank you so much, now the web site works fine!!
