### ISSUE TITLE
Buying credits : EUR versus USD

### ISSUE THREAD

**Issue by Gustry** [kartoza/projecta#1430]
It seems there is a bug with currencies on https://changelog.qgis.org/en/

1 : When I want to buy some credits : 
![ksnip_20220509-165805](https://user-images.githubusercontent.com/1609292/167441076-8959dc64-2ffc-4652-bec9-8c84b17bbbd8.png)

It's in EUR

2 : Clicking on the "Pay with strip" button : 

![ksnip_20220509-165840](https://user-images.githubusercontent.com/1609292/167441220-2ae2bb0f-ab9e-4f01-92b9-61b8d32f0caf.png)

Strip is mentioning USD when paying.
It's a straight conversion 20 EUR = 20 USD.
There is a bug.

Can you confirm which currency is used on the bank side ?

**Comment by dimasciput** [comment]
@Gustry yes it's a bug, it should be eur not usd. I'll deploy the fix today.

**Comment by Gustry** [comment]
Thanks @dimasciput

**Comment by dimasciput** [comment]
@Gustry can you try it again please

**Comment by Gustry** [comment]
Yes, I can see EUR now. I will try with a credit card now.
