### ISSUE TITLE
Error log in

### ISSUE THREAD

**Issue by AurelioMorales** [kartoza/projecta#1440]
Hi!,

There is an error when try to Log in:

_400
Erm....
It looks like you might be trying to do something you're not allowed to.
If this is not the case, try logging in. If you are already logged in, then you probably do not have permission. Sorry._

 and another error when trying to reset the password

_500
Ooops. Something broke....

The powers that be have been informed.
In the meantime, please form an orderly queue and head to the home page._

Thanks

**Comment by dimasciput** [comment]
Hi @AurelioMorales, thank you for the report. The issue has now been resolved. Please try again and let me know if the problem persists.

**Comment by AurelioMorales** [comment]
Solved! Thank you so much!
