### ISSUE TITLE
Organisation account with wrong credentials?

### ISSUE THREAD

**Issue by jvdkwast** [kartoza/projecta#1442]
I was helping the Australian Water School to setup the certificate for a course. After setting it up with my account, the admin of the Australian Water School wasn´t able to make any changes. Can you please check the account settings?

**Comment by dimasciput** [comment]
Hi @jvdkwast ,

You put the wrong owner account :
![image](https://user-images.githubusercontent.com/1979569/233847030-e622e3ad-3514-4aa8-9992-850d7e382fa8.png)

I have added the correct one, could you ask them to give it a try.

**Comment by jvdkwast** [comment]
Hi @dimasciput. Thanks! That was the issue.
