### ISSUE TITLE
SSL error for https://changelog.qgis.org/

### ISSUE THREAD

**Issue by spatialthoughts** [kartoza/projecta#1444]
The website is displaying an SSL error about an expired certificate. 

<img width="723" alt="Screenshot 2023-06-27 at 8 56 15 PM" src="https://github.com/kartoza/prj.app/assets/5227506/250cc49e-13b0-47dd-ae42-03444e0dfc51">

**Comment by dimasciput** [comment]
Hi, we are currently working to fix this issue.

**Comment by spatialthoughts** [comment]
The SSL certificate warning is gone now, but is causing other problems.

1. Participants are not receiving certification emails (verified in spam folder also)
2. Github login is not working for admin. (See screenshot)


Not sure if these are related to the SSL issue. If not, please let me know and I can file another issue

<img width="443" alt="github" src="https://github.com/kartoza/prj.app/assets/5227506/2922c852-be86-421b-9f97-86e1990c609b">

**Comment by dimasciput** [comment]
Thank you, @spatialthoughts,

I was just working on this today, so when you tried it, it wasn't finished yet.
Please try it again now.

**Comment by spatialthoughts** [comment]
Thanks. Looks good now. Closing.
