### ISSUE TITLE
Can't upload background image: "Request entity too large" error

### ISSUE THREAD

**Issue by johnwbryant** [kartoza/projecta#1451]
I'm trying to upload a 1.6 MB image as a background, and it's the same image I've used quite a few times. When I attempt it, I get this error:

![image](https://github.com/kartoza/prj.app/assets/1100600/2ed264cb-f83d-4d48-a053-432758340f3f)

**Comment by jvdkwast** [comment]
I have the same problem. Even if I compress the background I've always used under 1 MB the error shows up. For printing we still need to be able to add larger background files. If this can't be fixed soon, I need to print the certificates for tomorrow without a background. Please let me know how we can prioritize this.

**Comment by dimasciput** [comment]
Hi, let me quickly check the site.

**Comment by dimasciput** [comment]
@johnwbryant @jvdkwast, I've fixed it. I updated the nginx configuration to allow files larger than 1MB

**Comment by jvdkwast** [comment]
Great! I can confirm it works again. Thanks.

**Comment by johnwbryant** [comment]
Excellent! Tested and works for me. Thank you :)
