### ISSUE TITLE
Updating a course changes the dates

### ISSUE THREAD

**Issue by antoniolocandro** [kartoza/projecta#1454]
There is some weird bug where each time I come and edit a course the dates start to move around, I need to constantly update in order to get the correct ones
![image](https://github.com/kartoza/prj.app/assets/4627073/4eb16ff4-0037-4a03-9f60-70d545d93c30)

Also the selection box sometimes is greyed out
![image](https://github.com/kartoza/prj.app/assets/4627073/537dfedc-aa3f-4726-93b9-1d34af9dd4d6)

**Comment by geomenke** [comment]
@antoniolocandro are you still experiencing this? We have not been able to duplicate the issue.

**Comment by antoniolocandro** [comment]
can't seem to replicate now, so we can close.
