### ISSUE TITLE
Rejected organizations list empy

### ISSUE THREAD

**Issue by geomenke** [kartoza/projecta#1457]
I unfortunately had a reject an organization for QGIS certification. They didn't have sufficient contributions to QGIS.org and were not recommended by the national QGIS user group. However, no orgs show up in the Rejected list. Is this a permissions issue?

**Comment by jvdkwast** [comment]
I don't see the point of keeping a list of rejected organisations. As they are informed it's okay, so I suggest to remove this feature.

**Comment by geomenke** [comment]
There is also a button for viewing Rejected organizations from the Pending organizations page which needs to be removed ![image](https://github.com/user-attachments/assets/34e975d4-86c3-4f67-aa84-a978d8678f41)
