### ISSUE TITLE
Allow participants without a surname

### ISSUE THREAD

**Issue by spatialthoughts** [kartoza/projecta#1459]
Hi,

Currently the certification system doesn't allow adding participants without a Surname field. Many parts of the world only given names are used (see [Mononym](https://en.wikipedia.org/wiki/Mononym) )a nd thus it is not possible to issue a certificate without workarounds.

I would request a change in the system to name the Surname field optional to allow participants with a mononym to get a certificate

**Comment by jvdkwast** [comment]
I have a similar case now. Any follow-up?
