### ISSUE TITLE
Sponsors relation to a version needs to be removed

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#148]
![screenshot from 2015-11-09 12-07-06](https://cloud.githubusercontent.com/assets/178003/11031058/9aee5376-86da-11e5-9173-1d95b80a5076.png)

We need to manage the sponsors for a project and based on the renewal dates and the date of the changelog creation, we should list the active sponsors under the changelog description. Please chat to me if this is not clear.

**Comment by rischanlab** [comment]
Hi @timlinux I've removed the sponsor relation from version table. And about what you said, yes I am still not clear, where is the changelog description?

**Comment by rischanlab** [comment]
Refer to this PR https://github.com/kartoza/projecta/pull/150
