### ISSUE TITLE
We need forms and views for sponsor levels and periods

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#173]

**Comment by timlinux** [comment]
We need front end forms for these, available only to project owners (see #172 )

**Comment by rischanlab** [comment]
Hi @timlinux 

Now I am still working on this, and this is the view of sponsorship level and periods. 

Sponsorship Level
![screen shot 2015-12-28 at 11 24 29 am](https://cloud.githubusercontent.com/assets/2235894/12014116/5719e116-ad58-11e5-92f3-25f339176ce7.png)

Sponsorship Period

![screen shot 2015-12-28 at 11 42 07 am](https://cloud.githubusercontent.com/assets/2235894/12014118/59747926-ad58-11e5-9629-c40dba81bc4e.png)

Currently I add the those things to the nav-menu. 
![screen shot 2015-12-28 at 11 46 15 am](https://cloud.githubusercontent.com/assets/2235894/12014135/a2d1cf4c-ad58-11e5-901b-28c038d3050f.png) 
is that ok? 

So the logic that I used are:
* User (project's owner) add the sponsorship level. 
* User add the sponsorship period. 
* Then the last user add the sponsor (sponsorship period is one of the sponsor property).

am I in the right way, @timlinux ?

**Comment by timlinux** [comment]
@rischanlab please see my comments on your pull request for clarifications on above
