### ISSUE TITLE
Sponsors list should hide levels with no sponsors

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#218]
<img width="1183" alt="screen shot 2016-02-13 at 20 15 09" src="https://cloud.githubusercontent.com/assets/178003/13029269/205cf3fe-d290-11e5-8c12-264b9b216c7d.png">

**Comment by ann26** [comment]
Hi @timlinux , I think the current version of projecta only shows the sponsorship level when there is sponsor in it. Could you check it again please?

**Comment by cchristelis** [comment]
CNR
