### ISSUE TITLE
We need to generate a nice 'sponsors cloud'

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#230]
- generate a nice 'sponsors cloud’ image that can be placed onto promotional material (with logos scaled to the correct sizes based on sponsorship level)
- we need to add logo size constraints to sponsorship level model

**Comment by dimasciput** [comment]
Hi @timlinux 

What do you think about this:
![sponsors](https://cloud.githubusercontent.com/assets/1979569/13959157/8946060e-f085-11e5-9701-0e20060cf482.png)

I generated this on backend using [Pillow](https://pillow.readthedocs.org/en/3.1.x/) library, any feedback or suggestion would be appreciated. Thanks.

**Comment by dimasciput** [comment]
@timlinux , second update, I tried to centering each logo 
![download 4](https://cloud.githubusercontent.com/assets/1979569/13982352/2c1bf384-f11c-11e5-8ea0-02da083fa48e.png)

**Comment by timlinux** [comment]
That looks very nice (second version). Can you integrate this with the following tweaks:

When downloading the image have a separate view with these options:

a) ability to select which sponsorship levels to include in the image
b) ability to choose an image export (as per your example above) or an rst (with hyperlinks to sponsors) + sponsor images in a table as done in the changelog export) see for example https://www.qgis.org/en/site/about/sponsorship.html?highlight=sponsors

CC @andreasneumann


Can you add a button on the sponsors page (available to project admins only) that will let you get the
