### ISSUE TITLE
We need to show an edit link for sponsors if the user is logged in and staff

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#246]

**Comment by rischanlab** [comment]
* Make a management menu beside of add menu in the top of page.

**Comment by timlinux** [comment]
See also #255

**Comment by timlinux** [comment]
@sonlinux please check and close if done

**Comment by sonlinux** [comment]
Its done:
When am logged in and am staff user.

![sponso-edit-link-shows](https://user-images.githubusercontent.com/10270148/36418081-6f34e05e-1636-11e8-8621-043ba355e639.png)
