### ISSUE TITLE
Sponsors for a release need to be filtered for the project and the date

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#277]
There is a serious bug with the sponsors whereby if you set the release date for a release in one project, it will show on the release page sponsors from any other project.

<img width="1387" alt="screen shot 2016-03-31 at 13 36 43" src="https://cloud.githubusercontent.com/assets/178003/14167536/1eff7c90-f746-11e5-9a2e-ed648c9d22d6.png">

Note that you need to have a date for the version otherwise it does not replicate:

<img width="1210" alt="screen shot 2016-03-31 at 13 37 21" src="https://cloud.githubusercontent.com/assets/178003/14167565/50e68c58-f746-11e5-96b6-e59970bf6c14.png">

**Comment by rischanlab** [comment]
Thanks @dimasciput
