### ISSUE TITLE
We need a historical sponsors page

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#281]
from @andreasneumann : 

> For me - the most important thing I would expect from Projecta and sponsorship management is, that the list at http://www.qgis.org/en/site/about/sponsorship.html would be generated automatically from Projecta. Do you know if there is any progress on that?

**Comment by rischanlab** [comment]
Hi @timlinux I am still not sure about the title of this issue and the comment from Andreas Neumann. 
In the title of this task, you said that we need historical sponsors page, I understand that I need to make a page that contains past sponsors. 

Then, for the Andreas's comment do I need to consider it? I am still not sure about QGIS sponsors can be automatically generated from Projecta.

**Comment by timlinux** [comment]
Hi @rischanlab 

Ok Sorry I missed / forgot we already had this view. I guess the main problem is that it is not discoverable from the menus at the moment - I guess we will fix this when I push out the latest. @andreasneumann can you confirm if the link (http://changelog.inasafe.org/en/qgis/sponsors/list/) provides what you are looking for? I guess the next thing will be to find a way to make it embeddable in the main site.

**Comment by andreasneumann** [comment]
Hi @rischanlab and @timlinux 

The listing has still a few issues. For http://www.qgis.org/en/site/about/sponsorship.html we would need the following:

- List everything in a single page - don't require user to press next for several pages
- Order the sponsorships first by current vs. past and second by sponsor levels, e.g. first current silver sponsorings, then current bronze sponsorings - followed by past silver sponsorings and past bronze sponsorings
- Suppress sponsorship categories if there are no entries (e.g. don't list gold/platinum if we don't have any) - but this is less of an issue than the first two items.

Thanks again for working on this application!

Andreas

**Comment by timlinux** [comment]
@rischanlab can we sort this out for next week please?
