### ISSUE TITLE
We need to support animated GIF's

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#289]
Using licecap or silentcast it is easy to make animated GIF's. When images are uploaded to django though they are resized and converted to PNG. We need to update the logic so thumbs etc. can be created for animate GIF's without losing the animation.

**Comment by dimasciput** [comment]
@timlinux The conversion didn't happened when images are uploaded instead it converted and resized when the images are displayed through easy-thumbnail. 

So my approach is to check wether image that are going to displayed is gif or not. If it's gif then don't resize it.
See here : https://github.com/kartoza/projecta/pull/293
