### ISSUE TITLE
We need a view that can be used to generate the sponsors section in the QGIS about box

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#290]

**Comment by rischanlab** [comment]
Hi @timlinux could you explain more details about this? 
Did you mean we need sponsors list under this box?
![screen shot 2016-06-09 at 10 58 17 pm](https://cloud.githubusercontent.com/assets/2235894/15936562/b9740300-2e95-11e6-802d-259af186f938.png)

If yes there is so many sponsors for QGIS. 

Thanks.

**Comment by timlinux** [comment]
Ok here is a better explanation:
In QGIS we have help->QGIS Sponsors dialog:

![screen shot 2016-06-10 at 09 55 24](https://cloud.githubusercontent.com/assets/178003/15957780/a1e16c6c-2ef1-11e6-8096-d29bab250e3e.png)

Which shows like this:

![screen shot 2016-06-10 at 09 55 40](https://cloud.githubusercontent.com/assets/178003/15957784/a6f8fbb6-2ef1-11e6-81fd-8fe44ca909cc.png)

**Comment by timlinux** [comment]
This is a high priority issue - can we chat about it tomorrow?
