### ISSUE TITLE
500 on pending items

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#291]
http://changelog.qgis.org/en/qgis/2.16.0/pending-entry/list/ gives a 500 - currently I think there are actually no pending items there. Please check on sentry, see if you can replicate and then come up with a fix.

**Comment by timlinux** [comment]
See http://sentry.kartoza.com/kartoza/projecta-live/group/5106/

**Comment by dimasciput** [comment]
Hi @timlinux it seems I can't replicate this error, been trying it on the local and the server, got no 500 error message.
