### ISSUE TITLE
500 error trying to use social auth login stuff

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#296]
Currently github / google login is not working for me, nor is linking my account to them. Is there some more config work that I need to do? Can you check and fix please?

**Comment by dimasciput** [comment]
@timlinux 

For github you need to register the app here : https://github.com/settings/applications/new
After that you need to put client id and client secret to the projecta admin site, http://0.0.0.0:61202/en/site-admin/socialaccount/socialapp/

With the google, it's almost the same process. Here is more detailed guide http://django-allauth.readthedocs.io/en/latest/providers.html#google

**Comment by timlinux** [comment]
Thanks - what is the callback url I should use?

<img width="579" alt="screen shot 2016-06-22 at 00 18 46" src="https://cloud.githubusercontent.com/assets/178003/16248350/ec1bca68-380e-11e6-9ddc-de9e4d1def75.png">

**Comment by dimasciput** [comment]
The projecta url -> http://changelog.kartoza.com

**Comment by timlinux** [comment]
Ok thanks. I don't know if it is possible but I set up three separate auths:

- [ ] http://changelog.qgis.org - **works**
- [ ] http://changelog.kartoza.com - **500 error - see below**
- [ ] http://changelog.inasafe.org - **500 error - same as below**

Do you know if there is a strategy for us to support different domain aliases for the same site? I will remove the additional profiles for now.

```
MultipleObjectsReturned: get() returned more than one SocialApp -- it returned 3!

(2 additional frame(s) were not displayed)
...
  File "allauth/socialaccount/providers/oauth2/views.py", line 62, in view
    return self.dispatch(request, *args, **kwargs)
  File "allauth/socialaccount/providers/oauth2/views.py", line 88, in dispatch
    app = provider.get_app(self.request)
  File "allauth/socialaccount/providers/base.py", line 38, in get_app
    return SocialApp.objects.get_current(self.id, request)
  File "allauth/socialaccount/models.py", line 38, in get_current
    provider=provider)
```

**Comment by cchristelis** [comment]
This is no longer an issue.
