### ISSUE TITLE
Can not comment by using the disqus

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/projecta#313]
Problem
-----------
It seems I can no longer give a comment in the website.
![screen shot 2016-06-23 at 09 08 15](https://cloud.githubusercontent.com/assets/1421861/16294654/187351a8-3922-11e6-8fa5-96fc21426aca.png)

**Comment by dimasciput** [comment]
@ismailsunni 
I think you need to put disqus shorname in the secret.py files
`DISQUS_WEBSITE_SHORTNAME = 'kartoza'`

Or you can use fabfile to set up disqus shortname https://github.com/kartoza/projecta/blob/develop/fabfile.py#L464

**Comment by ismailsunni** [comment]
@dimasciput yeah, I was the one who set up the shortname before, but it seems it has gone. Perhaps just create new one for this changelog

**Comment by timlinux** [comment]
Ok I fixed it now thanks!
