### ISSUE TITLE
Clicking on project icon or project name should link you to the project landing page

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#324]
Click here on QGIS icon or QGIS name:

![screen shot 2016-07-01 at 12 37 42 am](https://cloud.githubusercontent.com/assets/178003/16506657/2205d742-3f24-11e6-9c95-89e32c4a5f81.png)

Should take you to here:

http://localhost:61202/en/qgis/

![screen shot 2016-07-01 at 12 38 56 am](https://cloud.githubusercontent.com/assets/178003/16506671/40e86472-3f24-11e6-87e2-d6980e475ae3.png)

**Comment by dimasciput** [comment]
Fixed on https://github.com/kartoza/projecta/pull/321
