### ISSUE TITLE
Duplicate sponsors in QGIS 2.16 release changelog

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#329]
I don't know if this is one for @andreasneumann or @rischanlab . We have duplicate entries for terrelogiche at http://changelog.qgis.org/en/qgis/version/2.16.0/ : 

![screen shot 2016-07-03 at 9 49 35 am](https://cloud.githubusercontent.com/assets/178003/16544369/dc67e1da-4103-11e6-8af1-65dad1a12950.png)

Thanks for picking that up @jef-n

**Comment by timlinux** [comment]
Its also strange that I do not see them here:

http://changelog.qgis.org/en/qgis/sponsorshipperiod/list/?page=1

**Comment by timlinux** [comment]
Looking on the backend it looks like one for you @andreasneumann 

![screen shot 2016-07-03 at 9 57 05 am](https://cloud.githubusercontent.com/assets/178003/16544403/934f3736-4104-11e6-82e1-a3044e4a269c.png)


Could you review what the correct dates should be?

**Comment by timlinux** [comment]
@rischanlab also note that you cannot see the TerreLogiche on the front end sponsorship period manager, only on the backend...

**Comment by rischanlab** [comment]
Hi @timlinux 
TerreLogiche sponsor is duplicated in entry. 
Please see this link [http://changelog.qgis.org/en/qgis/sponsorshipperiod/list/?page=6](http://changelog.qgis.org/en/qgis/sponsorshipperiod/list/?page=6)

This page still use old style so it has many pagination pages. After we merge [this](https://github.com/kartoza/projecta/pull/323#issuecomment-230171381) we will see more easier. 

![screen shot 2016-07-04 at 3 08 34 am](https://cloud.githubusercontent.com/assets/2235894/16547346/a4a8bc74-4194-11e6-90ec-b5e222570a39.png)

TerreLogiche
Start Date : June 1, 2016
End Date : June 1, 2017
http://changelog.qgis.org/en/qgis/sponsorshipperiod/rktyim/

TerreLogiche
Start Date : June 7, 2016
End Date : June 7, 2017
http://changelog.qgis.org/en/qgis/sponsorshipperiod/xgpucj/

Thanks.

**Comment by timlinux** [comment]
Hi @rischanlab thanks for looking - I think it is just a transcription error and the first entry should maybe be 2015-2016 or something - I will let @andreasneumann confirm that and then we can close this. 

By the way thanks for your work on generating the sponsors list - I am incorporating it in QGIS 2.16 here:

https://github.com/qgis/QGIS/pull/3264

**Comment by andreasneumann** [comment]
Hi @timlinux @rischanlab 

I cleared the double entry. Sorry about that.

Handling the sponsorships with these many pages and no clear ordering makes it a bit of a pain to correctly handle the sponsors. If it would be a single page, double entries would be easily detectable.

Andreas

**Comment by andreasneumann** [comment]
Oh - I see. I already get a single page list now - thanks - and sorry for the noise.

This improvement must be quite recent - thanks!

**Comment by timlinux** [comment]
Yes I am rolling out the tweaks and we make them....keep reporting your tweaks and we will make them when we can!
