### ISSUE TITLE
Order sponsors in their groups

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#333]
From @andreasneumann: 

```For the sponsors listing - is there a clear order within the same level at http://changelog.qgis.org/en/qgis/version/2.16.0/ ?

In my opinion, it should either be ordered alphabetically or by date. Neither seems to be the case. I would prefer alphabetic ordering with in each sponsorship level.```

I think it is actually better to order them with most recently added sponsors first to oldest sponsors last. That we they get the most visibility when they are new, degrading over time to the bottom of the list. What do you think @andreasneumann ?

**Comment by timlinux** [comment]
I had a look at the code - we are already wording sponsors by date they became sponsors which seems the most logical to me. Maybe we should add a sort button to let you sort it according to your preferred criteria?

**Comment by andreasneumann** [comment]
Really?

I don't think that http://changelog.qgis.org/en/qgis/version/2.16.0/ does match a date order. In what order? Rows first, or columns first? Or vice versa? Oldest or newest? By renewal date or first registration date? I can't see any logical temporal order there.

I would just do alphabetical order - seems more logical to me than date orders.

**Comment by timlinux** [comment]
@andreasneumann hoo sorry you are right - I looked again at the code:

https://github.com/kartoza/projecta/blob/develop/django_project/changes/models/version.py#L205

I will fix it.

**Comment by timlinux** [comment]
Ok how does this look?

![screen shot 2016-07-07 at 10 20 00 am](https://cloud.githubusercontent.com/assets/178003/16646798/70afc56c-442c-11e6-86dc-158ecb1ba8ec.png)

By the way I removed a lot of the detail around each sponsor so the sponsor cloud is less cluttered and fits in a smaller space...(done in a previous commit)

**Comment by andreasneumann** [comment]
Looks good - Thanks!

**Comment by timlinux** [comment]
Ok deployed to the live site @andreasneumann
