### ISSUE TITLE
rst export: please do not break lines on 70(?) chars length

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#340]
This breaks several rst constructs like links and comment/quotes (the ones with | in it)

**Comment by rischanlab** [comment]
Hi @timlinux we are using pypandoc for converting and I guess that is default from that library for rst converter they break every lines. I have tried to convert to another format and for the rst that is breaking line default. 

So, should I looking another package, or create a function for rst converter which will not breaking the lines? 

Thanks.

**Comment by rduivenvoorde** [comment]
@rischanlab I'm actually waiting for a 'go' on taking the rst and publishing it on the qgis website.

So unless you think to fix this in a few hours (and not generate other issues), I would not search for a solution.

I see pandoc has an option --no-wrap, can we maybe use that?

**Comment by rischanlab** [comment]
Thanks @rduivenvoorde I am working on this :)

**Comment by rischanlab** [comment]
Hi @rduivenvoorde thanks for your comment. It is working https://github.com/kartoza/projecta/pull/348

**Comment by dimasciput** [comment]
Fixed by #348
