### ISSUE TITLE
rst export: either a dummy image, or no place hoders

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#341]
the rest export contains image 'place holders'? Which end up in the 'images list as empty ones:

.. |image95| image::·                                                            
   :target: /media/ 

better to either add a dummy.png (or 1pxtransparent.png) to the export, OR leave images out from export if there is no image?

**Comment by rduivenvoorde** [comment]
@rischanlab fixing this would save me at least some time manual editing :-)

**Comment by rduivenvoorde** [comment]
@rischanlab Hi Rischan, how is this going? If you have this fixed, will you be able to deploy a new version too?
Because then I can get the rst and use it in qgis.org
If I find other problems, I'll fix them by hand for this release

**Comment by dimasciput** [comment]
Hi @rduivenvoorde, I'm taking this over. It will be quick fix, I will give you update later.
