### ISSUE TITLE
Display thumbnails in a modal window when we click on fullscreen

### ISSUE THREAD

**Issue by Gustry** [kartoza/projecta#343]
We can see a lot of GIF in the QGIS changelog. These thumbnails are too small to see so I have to click on the button to see it fullscreen. For now, it redirects to the GIF url like http://changelog.qgis.org/media/images/entries/53f72a9cf1bf32d73eb5174c37e54c60002b9707.gif
The user needs to use the "previous" button in the web browser to come back to the changelog.

It would be better to implement a javascript modal window to show the GIF and to stay on the URL http://changelog.qgis.org/en/qgis/version/2.16.0/

**Comment by timlinux** [comment]
Yes good idea. Maybe you would like to make a patch yourself using this:

http://www.w3schools.com/bootstrap/bootstrap_modal.asp

Here is the place to add logic:

https://github.com/kartoza/projecta/blob/develop/django_project/changes/templates/entry/includes/entry_detail.html#L37

I guess we should do it not only for GIF's but for any image....
