### ISSUE TITLE
Category management is broken

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#347]
* Creating a new category gives 500 when approving
* Creating a new category gives 500 when deleting a pending category
* Duplicate categories are allowed for a project (should be unique together)
* When editing an entry, category list in entry form is not filtered to the project of the entry
* Category list should be not paginated

**Comment by dimasciput** [comment]
- [x] Creating a new category gives 500 when approving
- [x] Creating a new category gives 500 when deleting a pending category
- [x] Duplicate categories are allowed for a project (should be unique together)
- [x] When editing an entry, category list in entry form is not filtered to the project of the entry
- [x] Category list should be not paginated
