### ISSUE TITLE
Projecta reveals personal data without login

### ISSUE THREAD

**Issue by andreasneumann** [kartoza/projecta#362]
I noticed that one can view personal data on Projecta without logging in - see f.e. http://changelog.qgis.org/en/qgis/sponsor/uhcnwf/ which reveals person names and E-Mail addresses without a Login. I think this should be avoided and should only be viewed after  #login.

**Comment by timlinux** [comment]
@dimasciput can you fix this with highest priority?

**Comment by timlinux** [comment]
Thanks @dimasciput . @andreasneumann I deployed @dimasciput's fix to the live site now...
