### ISSUE TITLE
Login with github is broken

### ISSUE THREAD

**Issue by cchristelis** [kartoza/projecta#364]
# Problem 

When I say sign-in with github and grant permissions I encounter a 500.

# Proposed Solution 

Fix this.

**Comment by cchristelis** [comment]
I got this token  944f9a6ca17c4e05874c05059600edc8

**Comment by dimasciput** [comment]
@cchristelis what url are you using? 

I think for now it only works on this domain http://changelog.qgis.org/

**Comment by timlinux** [comment]
Yes only works for the QGIS subdomain right now...

**Comment by timlinux** [comment]
Closing as this is covered by https://github.com/kartoza/projecta/issues/296
