### ISSUE TITLE
Cannot add new sponsor

### ISSUE THREAD

**Issue by andreasneumann** [kartoza/projecta#384]
I tried adding new sponsors to the QGIS sponsors list, but got the following error:

500
Ooops. Something broke....

The powers that be have been informed.
In the meantime, please form an orderly queue and head to the home page.

If you need assistance, you may reference this error as 1f96dfdab8c642789dcb40867a97e90d.

I used foreign characters, f.e. "ü" and "é" in the contact names, if that matters.

**Comment by Gustry** [comment]
Can we close this issue ?

**Comment by andreasneumann** [comment]
yes - no issues currently.
