### ISSUE TITLE
Limit the width of images to match the column width of the entry area

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#386]
Note that this should be checked on mobile browsers too to make sure the images scale nicely.

This would need to be done using CSS as the in-entry images are off site image links.

![2017-03-07 10_34_28-projecta_ entries -](https://cloud.githubusercontent.com/assets/178003/23648116/eaae05f4-0321-11e7-838f-080e01fc1189.png)

Outcome should be that images do not extend beyond the entry content area as shown above

**Comment by timlinux** [comment]
Simply using max-width: 100% on the img base class should do it:

![screencapture](https://cloud.githubusercontent.com/assets/178003/23648274/a00ac432-0322-11e7-8406-a1376cc8037b.gif)

**Comment by ann26** [comment]
I made pull request here: https://github.com/kartoza/projecta/pull/390

**Comment by Gustry** [comment]
Can we close this ticket now ?

**Comment by ann26** [comment]
Yes we can
