### ISSUE TITLE
error clicking on edit widget

### ISSUE THREAD

**Issue by gubuntu** [kartoza/projecta#388]
I logged in via Google as gavin@kartoza.com (before having a superuser account) and could see all content, with edit functionality. 

Clicked on version edit widget and got error page - infinite loop redirect

**Comment by timlinux** [comment]
@sonlinux please hide the buttons on version edit (and entry edit) if they user does not have the needed permissions. E.g. http://staging.changelog.qgis.org/en/qgis/version/list/ and on the entries here :http://staging.changelog.qgis.org/en/qgis/version/3.0.0/

**Comment by Gustry** [comment]
Maybe, while you will have look at hiding button @sonlinux, maybe you can implement a flag like this one is the view: https://github.com/kartoza/projecta/blob/develop/django_project/lesson/views/worksheet.py#L69

then in the template, you can just use this variable. It allows us later to easily comeback and add/remove new permissions in only one place.

**Comment by sonlinux** [comment]
Alright @Gustry ill just that.
Thanks
