### ISSUE TITLE
error after submit

### ISSUE THREAD

**Issue by gubuntu** [kartoza/projecta#389]
I edited version 4.0.0 (just some text changes) and clicked submit and got 404 on http://changelog.qgis.org/en/inasafe/version/4.0.0/ ... seems like it deleted it!

404

Sorry, but what you're looking for does not exist.

This could be for any number of reasons, but most likely you followed a broken link....

Here are the public projects you might be looking for:

InaSAFE | QGIS | Stream Feature Extractor

**Comment by gubuntu** [comment]
something to do with Tim moving it to Pending? Possibly while I was editing it?

**Comment by gubuntu** [comment]
I can still edit it (but not view it ) from http://changelog.qgis.org/en/inasafe/ where it's showing as released not pending

**Comment by ann26** [comment]
Hi @gubuntu I tried to edit the texts in there but everything seems to be working. 
Could you try to edit it again and let me know if it is still not working?

**Comment by cchristelis** [comment]
CNR
