### ISSUE TITLE
Update menu for training and certification

### ISSUE THREAD

**Issue by ann26** [kartoza/projecta#397]
Build menu for feature training and certification #392

**Comment by cchristelis** [comment]
This needs to be part of the certification model.

**Comment by ann26** [comment]
wireframe of the menus for certification app are described below:

project page with certification drop down menu:
![project_page 2 edited](https://cloud.githubusercontent.com/assets/26101337/24208209/95d6e998-0f55-11e7-9b62-f07cc5f50438.png)


Certifying organisation page:
![certifying_organisation edited](https://cloud.githubusercontent.com/assets/26101337/24206658/8035ad62-0f51-11e7-8055-9575dcd88438.png)


Add new or edit certifying organisation [ * ]
![add_new_and_edit](https://cloud.githubusercontent.com/assets/26101337/24206809/ef60159c-0f51-11e7-9938-66d937750689.png)


Certifying organisation detail view
![organisation_detail_view edited](https://cloud.githubusercontent.com/assets/26101337/24206832/000012a8-0f52-11e7-8205-ab8e179a813b.png)


delete certifying organisation page
![delete edited](https://cloud.githubusercontent.com/assets/26101337/24206865/18f6042a-0f52-11e7-98ee-38116e16ccbf.png)


Pending certifying organisation page
![view_pending edited](https://cloud.githubusercontent.com/assets/26101337/24206927/450228aa-0f52-11e7-8a12-0bc70e417901.png)


Training page
![training edited](https://cloud.githubusercontent.com/assets/26101337/24207112/a4a8a1f8-0f52-11e7-98a0-048a3123c35f.png)


training center view
![training_center edited](https://cloud.githubusercontent.com/assets/26101337/24207386/45fd5c06-0f53-11e7-9cde-459cdf7ce441.png)


training center add new or edit
![add_new_and_edit_training_center edited](https://cloud.githubusercontent.com/assets/26101337/24207445/6de0d374-0f53-11e7-9573-098898d8877b.png)


delete training center
![delete_training_center edited](https://cloud.githubusercontent.com/assets/26101337/24207481/903e86a0-0f53-11e7-929a-72ec7f98dd37.png)


training center detail view
![training_center_detail_view edited](https://cloud.githubusercontent.com/assets/26101337/24207650/0735c138-0f54-11e7-86d5-80ef0546a6c8.png)


course view
![course edited](https://cloud.githubusercontent.com/assets/26101337/24207693/1fe7f7d2-0f54-11e7-948c-68ed695750cb.png)


add course
![add_course edited](https://cloud.githubusercontent.com/assets/26101337/24207713/2c05fa46-0f54-11e7-916d-0e51c324e2c5.png)


delete course
![delete_course edited](https://cloud.githubusercontent.com/assets/26101337/24207729/382923e8-0f54-11e7-84a7-011b8c5b9d9d.png)


register attendee
![register_attendee edited](https://cloud.githubusercontent.com/assets/26101337/24207767/53ed9884-0f54-11e7-872e-c39eb517591d.png)


certificate welcome page
![certificate_welcome edited](https://cloud.githubusercontent.com/assets/26101337/24208662/c0342e66-0f56-11e7-9c2b-43a1872c357e.png)


validate a certificate 
- user can check if a certificate is valid or not.
![validate_certificate edited](https://cloud.githubusercontent.com/assets/26101337/24208820/33757984-0f57-11e7-8a3b-ef8102631562.png)


certificate is invalid
![certificate_invalid edited](https://cloud.githubusercontent.com/assets/26101337/24208949/812c74fc-0f57-11e7-83ab-c0c5d50902b4.png)


certificate is valid
![certificate_valid edited](https://cloud.githubusercontent.com/assets/26101337/24209104/e7139520-0f57-11e7-9666-70d1193fb9a2.png)


print certificate
![print_certificate edited](https://cloud.githubusercontent.com/assets/26101337/24208051/2a091a1a-0f55-11e7-932b-3986599b32b1.png)


payment
![payment](https://cloud.githubusercontent.com/assets/26101337/24209124/0251ddec-0f58-11e7-9f8a-a7b5ed82dc00.png)
after payment is generating the certificate in pdf

**Comment by ann26** [comment]
I updated the wireframes for certifying organisation and training center
