### ISSUE TITLE
Can't look pending detail

### ISSUE THREAD

**Issue by meomancer** [kartoza/projecta#413]
# Problem
Pending detail is just show in list with name on that, no detail show and can't look the detail. It is hard to accept some pending unless we look the admin section or we already know what the pending is.
![selection_040](https://cloud.githubusercontent.com/assets/4530905/25832790/06d92a14-3497-11e7-89fb-e83cedf66395.png)
![selection_041](https://cloud.githubusercontent.com/assets/4530905/25832789/06d9043a-3497-11e7-87ad-12e2235b704c.png)

# Solution
Maybe we could make new url, for pending?
For example:
we already has pending url
http://localhost:61202/id/inasafe/pending-sponsors/list/

maybe we could add slug with id of row?
http://localhost:61202/id/inasafe/pending-sponsors/2/

**Comment by meomancer** [comment]
is it valid issue @timlinux ?

**Comment by ann26** [comment]
Hi @meomancer , in the current version Projecta we can see the details on the organisation pending page
![screenshot from 2017-09-06 17-14-58](https://user-images.githubusercontent.com/26101337/30106881-21089304-9327-11e7-83d2-232de396c3cc.png)

**Comment by timlinux** [comment]
Won't fix - will be resolved through #806
