### ISSUE TITLE
After creating a new organization it should appear in the pending approval menu

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#429]
Please make sure if a user adds an organization the Pending Approval menu is updated

http://staging.changelog.qgis.org/en/qgis/pending-certifyingorganisation/list/

**Comment by timlinux** [comment]
@pcav for cc

**Comment by ann26** [comment]
Hi @timlinux , I checked in my local, the Pending Approval for certifying organisation is updated properly whenever a user adds an organisation. I cannot see the pending approval list in staging though, maybe because I am not an admin?
