### ISSUE TITLE
Certificate logos need to be rendered larger

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#484]
<img width="1651" alt="screen shot 2017-07-31 at 9 02 22 am" src="https://user-images.githubusercontent.com/178003/28766753-3d9d6c24-75d1-11e7-8222-5c26ac826c7a.png">

Can you make the project and certifying organization logos bigger in the layout please? Maybe 2x vertical and horizontal?

**Comment by ann26** [comment]
@timlinux will do
