### ISSUE TITLE
404 for unapproved pages

### ISSUE THREAD

**Issue by gubuntu** [kartoza/projecta#530]
If I click on an unapproved version or project I get a 404 - should be a nicer page with an explanation

**Comment by timlinux** [comment]
Please add this text:

"This project has not yet been approved - please wait until the project is approved and then revisit this page."

"This version has not yet been approved - please wait until the version is approved and then revisit this page."

**Comment by sonlinux** [comment]
- Unapproved projects are **not** clickable which seems okay for an unproved project. [it was fixed]

- And it is possible to click on an unapproved version and view details on it without errors. [it was fixed]
