### ISSUE TITLE
We need to specify preferred size for logos in project view

### ISSUE THREAD

**Issue by gubuntu** [kartoza/projecta#531]
specify logo image size else resize

It becomes a guessing game otherwise...

**Comment by mbernasocchi** [comment]
funny enough after writing a mail to tim I came to say: only thing not super good is the quality of our logo. we should give recommendations on size.

**Comment by timlinux** [comment]
@sonlinux lets recommend  squaare logo at e.g. 2048x2018  (make a test certificate to see if that gives good quality)
