### ISSUE TITLE
project should match on more than fist word

### ISSUE THREAD

**Issue by gubuntu** [kartoza/projecta#532]
I tried to add 'InaSAFE Realtime' and it complained that a project with the same name already existed. 

I had to make it 'InaSAFE-Realtime' to be accepted.

**Comment by gubuntu** [comment]
in fact, this seems to have created 'InaSAFE Realtime' despite complaining but clicking on it seems to have crashed Projecta - I get a 500

**Comment by gubuntu** [comment]
both InaSAFE-Realtime projects are giving a 500.

**Comment by ann26** [comment]
Hi @gubuntu , they are giving 500 because they have the same slug. Please check again I have fix it from admin panel.

**Comment by gubuntu** [comment]
OK I deleted one through admin (they both had the same slug too) and the realtime page is up again - but still an issue to be fixed

**Comment by gubuntu** [comment]
but the underlying cause in the OP should still be addressed.

**Comment by ann26** [comment]
Hi @gubuntu , I tried to reproduce the error in staging (both using staff account and non-staff account), but I didn't get this error. I'm not sure what was the problem that caused your error. But I think everything works now.

![peek 2017-09-20 12-40](https://user-images.githubusercontent.com/26101337/30628646-beee22ca-9e01-11e7-8498-052b21156c61.gif)
