### ISSUE TITLE
Academic title of lecturer/trainer needs to be added

### ISSUE THREAD

**Issue by jvdkwast** [kartoza/projecta#573]
The academic title (PhD, MSc, Prof,...) needs to be added to the name of the trainer so it will be printed on the certificate.

**Comment by timlinux** [comment]
One field for title (shown before name)
One field for degreee e.g. MSc. (shown in brackets after the name)

**Comment by timlinux** [comment]
Also should be shown on the certificate verification page e.g.

http://changelog.qgis.org/en/qgis/certificate/QGIS-49/
