### ISSUE TITLE
We should add an admin panel for certification

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#600]
The panel should allow the setting of a (list of) certification programme managers (from a subset of the project managers list see #596). This list of certification managers should receive notifications when a new registration request is received for a certifying organisation.

**Comment by ann26** [comment]
hi @timlinux , we now have certification managers in projecta, but we don't have the project managers yet. Should we introduce project managers in the project model? Or should we create a project managers model where there'll be subset of managers with different permissions and linked to project?

**Comment by linfiniti** [comment]
Hi Anita

I think they should be associated with the project model. I have a half done PR about it in the queue - maybe you can just pick up from there? We need a way for the project owner to manage the project managers list too on the edit project page too.

Regards

Tim

**Comment by ann26** [comment]
hi @timlinux , that's fine with me :)
so project managers are changelog managers?

**Comment by ann26** [comment]
done in #628
