### ISSUE TITLE
We need a feed of sponsors into the QGIS.org site

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#612]
Consider having an RSS feed or a url that will return zip containing the content

TODO Tim: Website: Include sponsors list from http://changelog.qgis.org/en/qgis/sponsors/list/ into http://www.qgis.org/en/site/about/sponsorship.html so Andreas doesn’t have to do twice the work (make an entry in the changelog application and manually update the website in Github)

**Comment by timlinux** [comment]
See for example news and maps on qgis.org home page. Pass url on to @rduivenvoorde

**Comment by rduivenvoorde** [comment]
FYI: we pull every hour some feeds to the webserver using:
https://github.com/qgis/QGIS-Website/blob/master/scripts/updatefeeds.sh

Then there is some (becoming comples) javascript code which injects it in the page:
https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/languageswitch.html#L122
for the frontpage it is called here:
https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/index.html#L286
