### ISSUE TITLE
Code markup should be a block display

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#630]
Currently the code snippets in markdown look ugly because the wrap on line length:

![screen shot 2017-11-14 at 15 15 48](https://user-images.githubusercontent.com/178003/32781829-144ff1e4-c94f-11e7-9fa7-33d638f88d10.png)

We should using display: block for this

**Comment by cchristelis** [comment]
This can be seen at http://changelog.inasafe.org/en/inasafe/version/4.3.0/
