### ISSUE TITLE
We should add preview support for certification course certificate

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#649]
When the user uploads a certificate template, we should show them a preview of the template as it will be rendered (using some lorem ipsum data for the participant details and real data for the logos etc.)

<img width="797" alt="screen shot 2017-12-13 at 11 24 35" src="https://user-images.githubusercontent.com/178003/33932627-20799826-dffc-11e7-8040-95a79d2e3328.png">

**Comment by mbernasocchi** [comment]
@timlinux +1 I just spent one credit to try and see how my certificates would look like. The alternative would be to start every account with one free credit to test the whole process

**Comment by timlinux** [comment]
@mbernasocchi since we work on an honour system, do not worry about spending credits on testing - you only need to pay for certificates that are actually used. Alternatively play around on our staging server http://staging.changelog.qgis.org

**Comment by timlinux** [comment]
Also please add some details on the course form on the ideal resolution etc to use for logos.
