### ISSUE TITLE
Sponsor entry is available to all projects on sponsorship period form

### ISSUE THREAD

**Issue by ann26** [kartoza/projecta#651]
Currently the sponsorship period form includes sponsors from all projects. So we can add a sponsor that is not registered to our project to our list of sponsorship period.

e.g. Sponsor A that is registered to QGIS project (has foreign key to QGIS project) can be added to sponsorship period list in Inasafe project. Thus the sponsorship period will have foreign key to Inasafe but Sponsor A has foreign key to QGIS. A problem will arise when a non staff user (project owner or sponsorship manager of Inasafe in this example) try to update the sponsor details. They will get 404 because they don't have the permissions to edit Sponsor A.

![screenshot from 2017-12-20 15-16-57](https://user-images.githubusercontent.com/26101337/34197394-e10cf9ba-e598-11e7-9322-2fd75a485400.png)

Should we restrict the sponsorship period form to only list sponsors that registered to that project @timlinux ?

**Comment by timlinux** [comment]
> Should we restrict the sponsorship period form to only list sponsors that registered to that project @timlinux ?

Absolutely yes thanks @ann26 In general all projects should be isolated from each other - it would be good to check around if there are other places where this is happening and fix it too...

Thanks!

**Comment by ann26** [comment]
ok @timlinux I will fix it :)
