### ISSUE TITLE
We need to improve the RSS feed

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#662]
Gents,

I thought to give the sponsorlist atom feed a chance today...

http://changelog.qgis.org/en/qgis/sponsors/rss/

http://changelog.qgis.org/en/qgis/sponsors/atom/

Some things I think we have to tackle:

* Images

Should we pull all images from the changelog server
http://changelog.qgis.org

OR should we do some downloading of a zip with all stuff and let it
unzip by some cronjob?

An example:

http://changelog.qgis.org/media/images/projects/5f50b148aecade6339b100f1ad30897b81ca9a09.jpg

* Http vs HttpS

Now that the website is 100% https, all links to images etc should also
go to httpS...
Which makes pointing to a http://changelog.qgis.org only possible if we
create a reverseproxy for it on qgis2 ?

* Sorting in list(s)

Currently both atom and rss entry are not easily suited to be used in
some javascript:

ATOM entry:

 <entry>
   <title>QGIS user group Switzerland</title>
   <link
href="http://changelog.kartoza.com/en/qgis/sponsorshipperiod/dwlwhd/"
rel="alternate"/>
   <id>http://changelog.kartoza.com/en/qgis/sponsorshipperiod/dwlwhd/</id>
   <summary type="html">&lt;div&gt;&lt;img
src="/media/images/projects/945e5e1463ca738057fd9bae0a427519ccbfef0d.png"
width="300px"&gt;&lt;/div&gt;&lt;p&gt;&lt;span&gt;Sponsorship level:
Gold : 9000 EUR&lt;/span&gt;&lt;br/&gt;&lt;span&gt;Sponsorship period:
21 June 201>
 </entry>

RSS entry:

   <item>
     <title>QGIS user group Switzerland</title>

<link>http://changelog.kartoza.com/en/qgis/sponsorshipperiod/dwlwhd/</link>
     <description>&lt;div&gt;&lt;img
src="/media/images/projects/945e5e1463ca738057fd9bae0a427519ccbfef0d.png"
width="300px"&gt;&lt;/div&gt;&lt;p&gt;&lt;span&gt;Sponsorship level:
Gold : 9000 EUR&lt;/span&gt;&lt;br/&gt;&lt;span&gt;Sponsorship period:
21 June 2017 - 21>

<guid>http://changelog.kartoza.com/en/qgis/sponsorshipperiod/dwlwhd/</guid>
   </item>

To know if it is a gold or silver or bronze sponsor I would need to
regexp in the description. Which is doable by the way...

But to order the sponsors. I think they are ordered by end-time of
sponsorship I have to pull out the Sponsorship period and try to parse
both begin and endtime etc etc

Can we maybe come up with a javascript friendlier format?
FYI this
https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/languageswitch.html
Is the already becoming pretty complicated script to handle the feeds we
have now...

Happy to do skype call if easier.

Regards,

Richard Duivenvoorde

CC @rduivenvoorde

**Comment by ThomasG77** [comment]
Look at https://jsonfeed.org. It's more or less JSON feed based "à la RSS/Atom".
It supports extensions where you could deal with your sponsoring fields requirements https://jsonfeed.org/version/1#extensions
