### ISSUE TITLE
Side panels are rendering really ugly

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#664]
![screen shot 2018-01-09 at 08 51 25](https://user-images.githubusercontent.com/178003/34708242-694ec19c-f51a-11e7-977e-20e3fb044b73.png)

@sonlinux can you please investigate and fix - ping me if it is not obvious from the screenie what the issue is

**Comment by sonlinux** [comment]
Alright @timlinux 
Am working on it this afternoon.
