### ISSUE TITLE
description field is too short

### ISSUE THREAD

**Issue by mbernasocchi** [kartoza/projecta#669]
the description field is super short. It would be good to allow a bit more of text so that a course can be explained

**Comment by geomenke** [comment]
+1 I just noticed this yesterday.

**Comment by timlinux** [comment]
@ann26 should be a quick fix, can you do this?

**Comment by timlinux** [comment]
@mbernasocchi btw can you give a bit more context or a screenshot so we can be sure that we are all talking about the same thing....

**Comment by mbernasocchi** [comment]
![image](https://user-images.githubusercontent.com/233663/35726301-b732f8d6-0804-11e8-827b-cd3dfb32f7d9.png)
