### ISSUE TITLE
[FEATURE] add a trained competences section in the certificate

### ISSUE THREAD

**Issue by mbernasocchi** [kartoza/projecta#670]
maybe we could add a trained competences in the certificate

```
Competences
* Plugin development
* Processing algorithm implementation
* PyQGIS Yoda```

**Comment by timlinux** [comment]
Note you can easily do this in the template too for now. Though yes we could add a field for this in the course form....

**Comment by Cracert** [comment]
In certificate preview only caption text (`With a trained competence in:`) is displayed, without content. Content is saved in course details.

Not tested with final certificate rendering.
