### ISSUE TITLE
Unable to add changelog to project even with write permisions

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/projecta#689]
# Problem
I have been granted access (manager) for a project but I get a 404 when I try to edit the project and also there is no option to add the changelog.

404 when editing the project
![error](https://user-images.githubusercontent.com/2510900/35043968-3ddc677a-fb97-11e7-86e9-637ed3fd84db.png)

No add option for changelog
![no_versions](https://user-images.githubusercontent.com/2510900/35043981-47ed87b2-fb97-11e7-86ba-52dec321e323.png)

# Solution
Make it happy

**Comment by ann26** [comment]
hi @NyakudyaA , by default the manager should not be able to edit the project, only the project owner and staff users can edit the project. The changelog manager, however, can add/edit/delete versions and category. The sponsorship manager can add/edit/delete sponsors and sponsorship and The certification manager can have the same access as owner only for certification app.

I fixed the missing add button in changelog (and some other permissions) here: https://github.com/kartoza/projecta/pull/731

**Comment by NyakudyaA** [comment]
Thanks, @ann26  will check as soon as it's merged and deployed
