### ISSUE TITLE
We need language switcher button

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/projecta#691]
Since we support mutliple language (at least for lesson app), we should put a button to switch between language easily. Currently, I do by changing the url (e.g. from `*/en/*` to `*/id/*`

**Comment by timlinux** [comment]
I think we can just add this in the account menu @sonlinux

**Comment by cchristelis** [comment]
@timlinux and @ismailsunni, I think we should maybe think of putting this into the menu ribbon? The reason for this suggestion is that if I come to a site and it is in a language that I don't understand, I am unlikely to search through menus to try and find the language button...

**Comment by timlinux** [comment]
> @timlinux and @ismailsunni, I think we should maybe think of putting this into the menu ribbon? The reason for this suggestion is that if I come to a site and it is in a language that I don't understand, I am unlikely to search through menus to try and find the language button...

Cracking good idea 👍

**Comment by Gustry** [comment]
big +1 of course ! Like in most websites:

<img width="1195" alt="screen shot 2018-02-21 at 14 54 46" src="https://user-images.githubusercontent.com/1609292/36478792-38607548-1717-11e8-8ea6-5a391fe11261.png">
