### ISSUE TITLE
Add link to explanation certification system on certificate

### ISSUE THREAD

**Issue by mbernasocchi** [kartoza/projecta#728]
we should have a link to the text mentioned in #727 on the certificate

**Comment by timlinux** [comment]
How about we put it on the certificate verification page rather?
That way we don't have to have another URL cast in stone in print.

**Comment by timlinux** [comment]
@sonlinux please do this one (adding it to the certificate verification page).

**Comment by sonlinux** [comment]
Alright @timlinux thanks.

**Comment by mbernasocchi** [comment]
@timlinux I was thinking about a more Course participant description

**Comment by sonlinux** [comment]
>@timlinux I was thinking about a more Course participant description

**Comment by sonlinux** [comment]
>@timlinux I was thinking about a more Course participant description

That would make sense as the certificate is issued for having attended a particular course.
