### ISSUE TITLE
Problems with category management in changes app

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#744]
- [ ] Pending categories do not show in awaiting approval menu so there is no way to know if new ones were added 

![screen shot 2018-02-05 at 09 33 41](https://user-images.githubusercontent.com/178003/35792830-b3372d92-0a57-11e8-9c97-9e3f99be1df4.png)

- [ ] When going to the category approval page there needs to be a unique filter so that the pending category only shows once (http://changelog.qgis.org/en/qgis/pending-category/list/)
- [ ] Category sorting page needs to have a unique filter - currently it repeats the same categories many times as per the screenie below: (http://changelog.qgis.org/en/qgis/category/order/)

![screen shot 2018-02-05 at 09 28 41](https://user-images.githubusercontent.com/178003/35792747-5089612e-0a57-11e8-8579-12ffbbcd790c.png)

**Comment by sonlinux** [comment]
After testing this in my local it seems that the issue was fixed in one of the PRs that have been merged.
- [ ] pending category shows in approval menue
- [ ] pending category shows once without duplicate
- [ ] category ordering page does not show duplicate entries
