### ISSUE TITLE
Email notification is not sent

### ISSUE THREAD

**Issue by ann26** [kartoza/projecta#762]
Email notification for approval that should be sent to managers and owner are not sent. The email notification that should be sent to organisation owners when first create the certifying organisation is not sent either.

**Comment by ann26** [comment]
So far, what I have found is that the smtp email is not sending the notification, though I sometimes got the email from projecta about error http headers. I tried to send the email notification using smtp gmail and it works. So somehow the smtp email is working only to send the email about errors but not the notification email. I am still continuing to investigate this.

**Comment by Gustry** [comment]
I think there are more emails which are not coming to me. Christo told me having some 500 errors on the production site. I was expecting some emails about the python exception, but nothing. Only the "Invalid HTTP host" is coming in my inbox.

I just loggin in the server to check:
```
ERROR 2018-02-12 15:26:46,794 base 473 140635681732352 Sentry responded with an error: HTTP Error 502: Bad Gateway (url: http://sentry.kartoza.com/api/8/store/)
{u'culprit': u'changes.views.sponsor in get_object',
 u'event_id': u'e7c93aaf5679417ea26a968550d62e10',
 u'exception': {u'values': [{u'module': u'changes.models.sponsorship_period',
                             u'stacktrace': {u'frames': [{u'abs_path': u'/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py',
                                                          u'context_line': u'                    response = wrapped_callback(request, *callback_args, **callback_kwargs)',
                                                          u'filename': u'django/core/handlers/base.py',
                                                          u'function': u'get_response',
                                                          u'in_app': False,
                                                          u'lineno': 132,
                                                          u'module': u'django.core.handlers.base',
                                                          u'post_context': [u'                except Exception as e:',
                                                                            u'                    # If the view raised an exception, run it through exception',
                                                                            u'                    # middleware, an
```

Error 500 yesterday at 15h26 in the sponsorship app. But no emails about this error.

Thanks for looking at this issue.

CCIMW

**Comment by ann26** [comment]
@Gustry me too, I've never gotten any emails about 500 errors from projecta, only Invalid HTTP_HOST header error

**Comment by Gustry** [comment]
I got everything working yesterday while fixing the unicode issue in the email.
https://github.com/kartoza/projecta/pull/801

I got the email in my inbox after my patch.

Can you check and close if possible?

**Comment by ann26** [comment]
Nice work @Gustry , I've tested it in staging and it is working, I got the email both for manager and organisation owner.
