### ISSUE TITLE
Error 500 when approving a certifying organization

### ISSUE THREAD

**Issue by geomenke** [kartoza/projecta#802]
I get this error when trying to approve QTIBIA Engineering.

**Comment by geomenke** [comment]
Yes just minutes ago

**Comment by Gustry** [comment]
I fixed this afternoon ! 
https://github.com/kartoza/projecta/pull/801

It just need to go in production

**Comment by timlinux** [comment]
Can you publish it @Gustry ?

**Comment by Gustry** [comment]
Done. Can you try again @geomenke ?

Thanks for reporting issues!

**Comment by Gustry** [comment]
I tried, it seems fixed on changelog.qgis.org. Feel free to reopen if needed. Thanks
