### ISSUE TITLE
Cannot add course type, conveners and training centre

### ISSUE THREAD

**Issue by mbernasocchi** [kartoza/projecta#807]
When logged in ad owner, I can *edit* any existing thing and add new courses but cannot add all the rest. the star button is never shown
![image](https://user-images.githubusercontent.com/233663/36860637-28baf14c-1d82-11e8-8763-95368f6489a8.png) the screenshot is while hovering the Course types box
I used to be able to do this or I'm I missing something?

**Comment by jvdkwast** [comment]
Here same. I can't add course types, while I could in the past

**Comment by timlinux** [comment]
@sonlinux can you bump this up your priority list please?

**Comment by sonlinux** [comment]
>@sonlinux can you bump this up your priority list please?

The PR has been ready @timlinux 
https://github.com/kartoza/projecta/pull/816
Thanks
