### ISSUE TITLE
i18n Supports.

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/projecta#821]
When I tried to print the PDF in Bahasa Indonesia, e.g. http://changelog.qgis.org/id/qgis/section/introduction-qgis-1/print/77/

I got these parts are not translated.
<img width="997" alt="screen shot 2018-03-08 at 16 30 18" src="https://user-images.githubusercontent.com/1421861/37143702-84ce850e-22ee-11e8-88e9-4efb51ef04bb.png">

The other pars, `More about` is translated because it's in the model.

I think we should start making projecta support i18n (not only for the lesson app), but also the text.

cc @timlinux

**Comment by Gustry** [comment]
Yes, it was expected, sorry. There are a few strings hardcoded in the HTML template. Need to use the special template tags. But in Transifex, you will have a lot of strings.

**Comment by Gustry** [comment]
Also "Section", "You try", "Goal" ... in your PDF

**Comment by ismailsunni** [comment]
Yes, it's in the template. So it seems we need to translate all of the strings. Well, at least for the module PDF first.
