### ISSUE TITLE
Edit options missing for certifying organisations

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#829]
@sonlinux we have had some regressions in the certification platform that need to be fixed urgently.

The organisation owner is no longer able to edit course types and other content on  the certification organiation page e.g.: 

http://staging.changelog.qgis.org/en/qgis/certifyingorganisation/ihe-delft-institute-for-water-education/

There are also some strange things in the code like this can_delete sentinel which actually also provides edit access. This should be made logically consistent e.g.:

``projecta/django_project/certification/templates/certifying_organisation/detail.html``

```
        {% if user_can_delete %}
        <td style="padding-right: 0">
             <div class="btn-group pull-right button-action" style="display: none;">
                <a class="btn btn-default btn-xs btn-delete tooltip-toggle"
                   href='{% url "course-delete" project_slug=certifyingorganisation.project.slug organisation_slug=certifyingorganisation.slug slug=course.slug %}'
                   data-title="Delete">
                    <span class="glyphicon glyphicon-minus"></span>
                </a>
                <a class="btn btn-default btn-xs tooltip-toggle"
                   href='{% url "course-update" project_slug=certifyingorganisation.project.slug organisation_slug=certifyingorganisation.slug slug=course.slug %}'
                   data-title="Edit">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                 <a class="btn btn-default btn-xs btn-view tooltip-toggle"
                    href='{% url 'course-detail' project_slug=certifyingorganisation.project.slug organisation_slug=certifyingorganisation.slug slug=course.slug %}'
                    data-title="View">
                    <span class="glyphicon glyphicon-eye-open"></span>
                </a>
            </div>
        </td>
        {% elif user == course.course_convener.user %}
```

@sonlinux please fix this ASAP - people are trying to use the system and everything needs to work properly.

See also #667

**Comment by sonlinux** [comment]
Okay @timlinux 
I'll fix

**Comment by sonlinux** [comment]
We have merged the patch in PR but we decided to keep the ticket open in case of any tweaks that may arise.
