### ISSUE TITLE
show more information about pending items

### ISSUE THREAD

**Issue by gubuntu** [kartoza/projecta#830]
It's difficult to make a decision about approving a pending project (or other item) if there's no information about who proposed it, what it's about etc.

**Comment by timlinux** [comment]
See #806 - we are planning to remove the moderation queue in favour of assigning granular permissions to specific users who can do specific actions on the platform. There is another ticket also for deploying django easy audit so we can have an audit trail on actions taken against any object. I am going to close this in favour of #806 for now.
