### ISSUE TITLE
more flexible image size and layout

### ISSUE THREAD

**Issue by gubuntu** [kartoza/projecta#835]
The rigid image specification and handling doesn't allow for alternative sizes or layouts e.g. http://changelog.qgis.org/en/inasafe-realtime2/section/introduction-to-inasafe-realtime/detail/40/

maybe the layout can be made more responsive to retain image aspect ratios, within certain bounds?

Also, the css should not warp an image by changing its aspect ratio. Rather resize it proportionally.

And if it has to be forced into a restricted space then enable the same funcitonality as with the 'more about' image - click on it to see the full version.

**Comment by Gustry** [comment]
If you tweak the template, don't forget the PDF rendering too ;-)
