### ISSUE TITLE
Lets remove the vertical constraint on lesson images

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#840]
See e.g. http://changelog.qgis.org/en/inasafe/section/advanced-inasafe-customisation/detail/133/

<img width="1220" alt="screen shot 2018-03-12 at 13 56 54" src="https://user-images.githubusercontent.com/178003/37282509-55f3eac8-25fd-11e8-806d-14a61142d432.png">

Let's just maintain the original aspect ratio.

**Comment by Gustry** [comment]
If you tweak the template, don't forget the PDF rendering too ;-)
