### ISSUE TITLE
Make lesson exercise span the whole table

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#842]
I think since we cant get the table next to the exercise, let us at least make the exercise content span the whole page.

<img width="1080" alt="screen shot 2018-03-12 at 13 59 54" src="https://user-images.githubusercontent.com/178003/37282634-d1abbfe2-25fd-11e8-9a3e-47c67311e5ae.png">

See e.g. http://changelog.qgis.org/en/inasafe/section/advanced-inasafe-customisation/detail/133/

**Comment by timlinux** [comment]
Please assign to @sonlinux if you don't have time to do it this week.

**Comment by Gustry** [comment]
If you tweak the template, don't forget the PDF rendering too ;-)
