### ISSUE TITLE
More about section in lesson should span 

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#843]
Same as #842 make the 'more about' section and place any associated image above it, scaled to page width and maintaining aspect ratio.

<img width="1219" alt="screen shot 2018-03-12 at 14 03 45" src="https://user-images.githubusercontent.com/178003/37283022-25f24ce6-25ff-11e8-8f23-96f03e41b0ff.png">

Assign to @sonlinux if you don't have time to do it

**Comment by Gustry** [comment]
If you tweak the template, don't forget the PDF rendering too ;-)
