### ISSUE TITLE
Word limits in lessons are too restrictive

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#850]
@ismailsunni the word limits on the lesson app are too restrictive. I am trying to add the following content to the creating a new hazard lesson and I cant fit it in:

----

In this exercise, we are going to use chemical spills as an example of a new type of hazard we would like to add to InaSAFE.  We are going to be changing the source code of InaSAFE but do not be afraid of breaking anything - if it all goes wrong you can simply re-install InaSAFE from the plugin manager. Any changes made to source files should be made using a text editor such as Notepad++ or Sublime Edit.

* To start, open the Impact Function Centric Wizard and take note of the available hazard types catered for on the first screen.
* Next open the sample project provided. In that project you will see a fictitious chemical spill incident.
* Note that for all instructions, ``~`` refers to your home directory.
* Note also that whenever making changes to your hazard definitions, you will need to restart QGIS in order to test the changes.
* Navigate to your working directory using your file manager.
* Edit the file containing hazard definitions using your text editor.
* Locate the definition of ``hazard_generic`` in the hazard file and copy the entire block (look for the closing ``}`` which ends the block.
* Paste the block in after the end of the ``hazard_generic`` block effectively giving you two identical blocks.
* In the new block edit the contents as per the specification table below for ‘hazard block’.
* Once you have finished editing the hazard block, add a new entry to the ``hazard_all`` block at the bottom of ``hazard.py`` as per the All hazards block specification below.
* Save your edits to hazard.py and restart QGIS.
* Open the Impact Function Centric Wizard. Do you see the new hazard type listed there?
* Currently the chemical spill hazard is using the same classification as the generic hazard (I.e. high, medium, low hazard). In the next steps we will create a new classification specification. 
* Open the file called ``hazard_classification.py``.
* Look for the block called ``generic_hazard_classes`` and make a copy of it.
* In the copied block, replace all items as listed in the Hazard classification block items below.
* Add your new hazard classification to the ‘hazard_classification’ list at the bottom of the file in the ‘types’ section.
* You need to tell your hazard definition that it supports this new hazard classification. Do this by editing ``hazard.py`` again and changing your ‘``classifications': [generic_hazard_classes, chemical_spill_hazard_classes], ``
* Save your edits and restart QGIS and add the layers from the sample data provided as per the Input layers listed in teh specification below.
* Now run the keywords wizard and see if you can define the hazard class and hazard classification for the chemical spill layer, then run the analysis.
* Lastly run the analysis as per the Analysis question in the specification below.

---

Can you please remove the word limits for all the text fields in the lesson app and then paste in my text above into exercise description for the lesson at:

http://changelog.qgis.org/en/inasafe/section/advanced-inasafe-customisation/detail/135/

**Comment by ismailsunni** [comment]
I have fixed the word limit and update the worksheet: http://changelog.qgis.org/en/inasafe/section/advanced-inasafe-customisation/detail/135/
