### ISSUE TITLE
Funny/Strange Button Layout

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/projecta#854]
Make it happy :D 

<img width="1221" alt="screen shot 2018-03-14 at 10 47 52" src="https://user-images.githubusercontent.com/1421861/37382402-4772dfbc-2775-11e8-91c2-14ebc22bf753.png">

from http://changelog.qgis.org/en/inasafe-realtime2/section/introduction-to-inasafe-realtime/detail/40/

**Comment by timlinux** [comment]
Also for questions the layout is hinky

<img width="1154" alt="screen shot 2018-03-15 at 11 35 11" src="https://user-images.githubusercontent.com/178003/37455178-291f5a60-2845-11e8-846f-c58df1ae0a30.png">
