### ISSUE TITLE
Lesson Cosmetics

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/projecta#882]
From this site: http://changelog.inasafe.org/en/inasafe/section/home-assignments/detail/138/

There are some unavailable items in the lessons. We should not show this to the common users or when we print it. So, things to do:

- [ ] Only show available items to the normal user (not staff or admin). We still need to show it to admin/staff so that we can make an edit.
- [ ] When we print it, we should not show any unavailable items (for all users), since we want to print it.

**Comment by ismailsunni** [comment]
<img width="666" alt="screen shot 2018-04-10 at 12 59 28" src="https://user-images.githubusercontent.com/1421861/38538684-18cbbdf0-3cbf-11e8-91ee-0883ec10ff25.png">


Since some of them are mandatory fields, we use a trick to put one or more space characters on it. So, you need check whether it's only space or not only space.

**Comment by timlinux** [comment]
Lets change this to make it not mandatory except for the title and intro content. Also if all fields is null leave it and its section out. It will make it flexible for us how we compile the lessons....

**Comment by ismailsunni** [comment]
Hi @sonlinux 
I still got the empty goal:
<img width="934" alt="screen shot 2018-04-12 at 09 14 00" src="https://user-images.githubusercontent.com/1421861/38652864-0ebc3172-3e32-11e8-9348-086ace81a3a5.png">

Please check the homework 3 in the InaSAFE lesson: http://changelog.inasafe.org/en/inasafe/section/home-assignments/detail/138/
