### ISSUE TITLE
Reshape html summary in atom/rss sponsors feed

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#904]
Currently the sponsor items are looking like this:

```
<div>
<img
src="/media/images/projects/b9c08a00a74cba8e406e97f94a1f90595f5ac39d.png"
width="300px">
</div>
<p><span>Sponsorship level: Gold : 9000 EUR</span>
<br/>
<span>Sponsorship period: 21 June 2017 - 21 June 2018</span><br/>
<span>Amount sponsored: EUR 9000.00<span>
</p>
```

Is it (easy) possible in this html to change the following:
- make the img-element a full url (as I use the feed in qgis.org and it is easiest to just retrieve the images from changelog.qgis.org
- add some classes to the img-element and the p-element as then I can do some more styling.

An example:

```
<div>
<img src="http://changelog.qgis.org/media/images/projects/..5ac39d.png"
class="sponsor_img gold">
</div>
<p class="sponsor_body gold">
<span>Sponsorship level: Gold : 9000 EUR</span>
<br/>
<span>Sponsorship period: 21 June 2017 - 21 June 2018</span>
<br/>
<span>Amount sponsored: EUR 9000.00<span>
</p>
```

**Comment by ann26** [comment]
hi @rduivenvoorde ,
we have the `image_url` property for each sponsor using the full url in this page http://changelog.qgis.org/en/qgis/sponsors/json/ 
will that be able to help you?

**Comment by rduivenvoorde** [comment]
@ann26 thanks for this.

Yes, I know it is there. It is also available in the atom version I use. BUT my 'problem' is that I do want to take over the 'summary' (in atom) or 'description' (in rss) as verbatim as possible.
I have to create some html, and can not easily extract the information I need from both feeds:
- an description (NOT holding an relative url, OR holding a full url)
- an type of sponor (so I can style the different types gold/silver/bronze) differently
- an url
(- optionally(!) the sponsor start/end period so I can check validity)
If we are able to create/change the summary/description in the way I describe above, it will much easier for me to extract/use the information.
Note that I already can build it by running over the items and do a lot of guessing and 'find-replacing' of the summary to mold it in the way I can use it in the website sponsor list.

BUT if there is no way to influence the description/summary, for example if you use a library for it that lacks that functionality, then I'll use what there is now....
See #903 for another issue which makes I cannot easily use the feeds.
