### ISSUE TITLE
Only staff members see the 'create new issue' button

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#905]
See https://lists.osgeo.org/pipermail/qgis-developer/2018-May/053161.html

When you are a staff member and go to: 
http://changelog.qgis.org/en/qgis/version/3.0.0/
You are able to create a new entry.

But non staff users do not see this button:

![selection_413](https://user-images.githubusercontent.com/731673/39465245-90215b26-4d22-11e8-8bdb-c8011c0319bf.png)

**Comment by timlinux** [comment]
@sonlinux please fix ASAP
