### ISSUE TITLE
Fresh added items are only visible for staff members

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/projecta#908]
See discussion:

https://lists.osgeo.org/pipermail/qgis-developer/2018-May/053200.html

I think for a next version it would be better if all people could add items AND keep seeing them.

The 'approval' process is not transparent for users, and for them they 'just loose their edits'.

**Comment by timlinux** [comment]
Duplicates #806 - @rduivenvoorde yeah I agree, we plan to do away with the moderation stuff....

**Comment by timlinux** [comment]
Can youplease make this happen @sonlinux ?
