### ISSUE TITLE
Project block should make it clear that versions listed are only two most recent

### ISSUE THREAD

**Issue by timlinux** [kartoza/projecta#98]
# Problem

When you look at the project block, it isn't clear that there may be more versions than listed:

![selection_001](https://cloud.githubusercontent.com/assets/178003/2953990/336a9e7c-da69-11e3-8541-3ae2ec014133.png)

Actually when you click into the project you see this:

![selection_002](https://cloud.githubusercontent.com/assets/178003/2953994/3dcd3186-da69-11e3-939b-e01c77c7a462.png)

# Proposed solution

Simply adding the the word 'Latest' in front of the project block versions list will be a good start.

![selection_001](https://cloud.githubusercontent.com/assets/178003/2954000/690b3b04-da69-11e3-9e88-10ebc2db6b03.png)

We could also think about making that list scrollable but it might look crap.

# Expected outcome

User should be clear that there are more versions for this project.

**Comment by timlinux** [comment]
At the moment I have changed it to show last 5 versions, but essence of the ticket remains...

**Comment by rischanlab** [comment]
Hi @timlinux I proposed this solution 

![screen shot 2015-10-05 at 10 48 18 am](https://cloud.githubusercontent.com/assets/2235894/10272768/0ae183a8-6b4f-11e5-947d-ed6af5e760d9.png)

if you agree you can merge my pull request 
thanks
